"""Auto-generated MCP server from package 'pandas'.

Generated by auto-mcp.
Modules analyzed: 1
Methods exposed: 530 tools, 0 resources, 0 prompts
"""

from mcp.server.fastmcp import FastMCP

import pandas

# Create MCP server
mcp = FastMCP(name="pandas-mcp-server")

# Tools

@mcp.tool(name="array")
def array(*args, **kwargs):
    """Create an array."""
    return pandas.array(*args, **kwargs)


@mcp.tool(name="bdate_range")
def bdate_range(*args, **kwargs):
    """Return a fixed frequency DatetimeIndex with business day as the default."""
    return pandas.bdate_range(*args, **kwargs)


@mcp.tool(name="concat")
def concat(*args, **kwargs):
    """Concatenate pandas objects along a particular axis."""
    return pandas.concat(*args, **kwargs)


@mcp.tool(name="crosstab")
def crosstab(*args, **kwargs):
    """Compute a simple cross tabulation of two (or more) factors."""
    return pandas.crosstab(*args, **kwargs)


@mcp.tool(name="cut")
def cut(*args, **kwargs):
    """Bin values into discrete intervals."""
    return pandas.cut(*args, **kwargs)


@mcp.tool(name="date_range")
def date_range(*args, **kwargs):
    """Return a fixed frequency DatetimeIndex."""
    return pandas.date_range(*args, **kwargs)


@mcp.tool(name="eval")
def eval(*args, **kwargs):
    """Evaluate a Python expression as a string using various backends."""
    return pandas.eval(*args, **kwargs)


@mcp.tool(name="factorize")
def factorize(*args, **kwargs):
    """Encode the object as an enumerated type or categorical variable."""
    return pandas.factorize(*args, **kwargs)


@mcp.tool(name="from_dummies")
def from_dummies(*args, **kwargs):
    """Create a categorical ``DataFrame`` from a ``DataFrame`` of dummy variables."""
    return pandas.from_dummies(*args, **kwargs)


@mcp.tool(name="get_dummies")
def get_dummies(*args, **kwargs):
    """Convert categorical variable into dummy/indicator variables."""
    return pandas.get_dummies(*args, **kwargs)


@mcp.tool(name="infer_freq")
def infer_freq(*args, **kwargs):
    """Infer the most likely frequency given the input index."""
    return pandas.infer_freq(*args, **kwargs)


@mcp.tool(name="interval_range")
def interval_range(*args, **kwargs):
    """Return a fixed frequency IntervalIndex."""
    return pandas.interval_range(*args, **kwargs)


@mcp.tool(name="isna")
def isna(*args, **kwargs):
    """Detect missing values for an array-like object."""
    return pandas.isna(*args, **kwargs)


@mcp.tool(name="isna")
def isna(*args, **kwargs):
    """Detect missing values for an array-like object."""
    return pandas.isna(*args, **kwargs)


@mcp.tool(name="json_normalize")
def json_normalize(*args, **kwargs):
    """Normalize semi-structured JSON data into a flat table."""
    return pandas.json_normalize(*args, **kwargs)


@mcp.tool(name="lreshape")
def lreshape(*args, **kwargs):
    """Reshape wide-format data to long."""
    return pandas.lreshape(*args, **kwargs)


@mcp.tool(name="melt")
def melt(*args, **kwargs):
    """Unpivot a DataFrame from wide to long format, optionally leaving identifiers set."""
    return pandas.melt(*args, **kwargs)


@mcp.tool(name="merge")
def merge(*args, **kwargs):
    """Merge DataFrame or named Series objects with a database-style join."""
    return pandas.merge(*args, **kwargs)


@mcp.tool(name="merge_asof")
def merge_asof(*args, **kwargs):
    """Perform a merge by key distance."""
    return pandas.merge_asof(*args, **kwargs)


@mcp.tool(name="merge_ordered")
def merge_ordered(*args, **kwargs):
    """Perform a merge for ordered data with optional filling/interpolation."""
    return pandas.merge_ordered(*args, **kwargs)


@mcp.tool(name="notna")
def notna(*args, **kwargs):
    """Detect non-missing values for an array-like object."""
    return pandas.notna(*args, **kwargs)


@mcp.tool(name="notna")
def notna(*args, **kwargs):
    """Detect non-missing values for an array-like object."""
    return pandas.notna(*args, **kwargs)


@mcp.tool(name="period_range")
def period_range(*args, **kwargs):
    """Return a fixed frequency PeriodIndex."""
    return pandas.period_range(*args, **kwargs)


@mcp.tool(name="pivot")
def pivot(*args, **kwargs):
    """Return reshaped DataFrame organized by given index / column values."""
    return pandas.pivot(*args, **kwargs)


@mcp.tool(name="pivot_table")
def pivot_table(*args, **kwargs):
    """Create a spreadsheet-style pivot table as a DataFrame."""
    return pandas.pivot_table(*args, **kwargs)


@mcp.tool(name="qcut")
def qcut(*args, **kwargs):
    """Quantile-based discretization function."""
    return pandas.qcut(*args, **kwargs)


@mcp.tool(name="read_clipboard")
def read_clipboard(*args, **kwargs):
    """Read text from clipboard and pass to :func:`~pandas."""
    return pandas.read_clipboard(*args, **kwargs)


@mcp.tool(name="read_csv")
def read_csv(*args, **kwargs):
    """Read a comma-separated values (csv) file into DataFrame."""
    return pandas.read_csv(*args, **kwargs)


@mcp.tool(name="read_excel")
def read_excel(*args, **kwargs):
    """Read an Excel file into a ``pandas`` ``DataFrame``."""
    return pandas.read_excel(*args, **kwargs)


@mcp.tool(name="read_feather")
def read_feather(*args, **kwargs):
    """Load a feather-format object from the file path."""
    return pandas.read_feather(*args, **kwargs)


@mcp.tool(name="read_fwf")
def read_fwf(*args, **kwargs):
    """Read a table of fixed-width formatted lines into DataFrame."""
    return pandas.read_fwf(*args, **kwargs)


@mcp.tool(name="read_gbq")
def read_gbq(*args, **kwargs):
    """Load data from Google BigQuery."""
    return pandas.read_gbq(*args, **kwargs)


@mcp.tool(name="read_hdf")
def read_hdf(*args, **kwargs):
    """Read from the store, close it if we opened it."""
    return pandas.read_hdf(*args, **kwargs)


@mcp.tool(name="read_html")
def read_html(*args, **kwargs):
    """Read HTML tables into a ``list`` of ``DataFrame`` objects."""
    return pandas.read_html(*args, **kwargs)


@mcp.tool(name="read_json")
def read_json(*args, **kwargs):
    """Convert a JSON string to pandas object."""
    return pandas.read_json(*args, **kwargs)


@mcp.tool(name="read_orc")
def read_orc(*args, **kwargs):
    """Load an ORC object from the file path, returning a DataFrame."""
    return pandas.read_orc(*args, **kwargs)


@mcp.tool(name="read_parquet")
def read_parquet(*args, **kwargs):
    """Load a parquet object from the file path, returning a DataFrame."""
    return pandas.read_parquet(*args, **kwargs)


@mcp.tool(name="read_pickle")
def read_pickle(*args, **kwargs):
    """Load pickled pandas object (or any object) from file."""
    return pandas.read_pickle(*args, **kwargs)


@mcp.tool(name="read_sas")
def read_sas(*args, **kwargs):
    """Read SAS files stored as either XPORT or SAS7BDAT format files."""
    return pandas.read_sas(*args, **kwargs)


@mcp.tool(name="read_spss")
def read_spss(*args, **kwargs):
    """Load an SPSS file from the file path, returning a DataFrame."""
    return pandas.read_spss(*args, **kwargs)


@mcp.tool(name="read_sql")
def read_sql(*args, **kwargs):
    """Read SQL query or database table into a DataFrame."""
    return pandas.read_sql(*args, **kwargs)


@mcp.tool(name="read_sql_query")
def read_sql_query(*args, **kwargs):
    """Read SQL query into a DataFrame."""
    return pandas.read_sql_query(*args, **kwargs)


@mcp.tool(name="read_sql_table")
def read_sql_table(*args, **kwargs):
    """Read SQL database table into a DataFrame."""
    return pandas.read_sql_table(*args, **kwargs)


@mcp.tool(name="read_stata")
def read_stata(*args, **kwargs):
    """Read Stata file into DataFrame."""
    return pandas.read_stata(*args, **kwargs)


@mcp.tool(name="read_table")
def read_table(*args, **kwargs):
    """Read general delimited file into DataFrame."""
    return pandas.read_table(*args, **kwargs)


@mcp.tool(name="read_xml")
def read_xml(*args, **kwargs):
    """Read XML document into a :class:`~pandas."""
    return pandas.read_xml(*args, **kwargs)


@mcp.tool(name="set_eng_float_format")
def set_eng_float_format(*args, **kwargs):
    """Format float representation in DataFrame with SI notation."""
    return pandas.set_eng_float_format(*args, **kwargs)


@mcp.tool(name="show_versions")
def show_versions(*args, **kwargs):
    """Provide useful information, important for bug reports."""
    return pandas.show_versions(*args, **kwargs)


@mcp.tool(name="test")
def test(*args, **kwargs):
    """Run the pandas test suite using pytest."""
    return pandas.test(*args, **kwargs)


@mcp.tool(name="timedelta_range")
def timedelta_range(*args, **kwargs):
    """Return a fixed frequency TimedeltaIndex with day as the default."""
    return pandas.timedelta_range(*args, **kwargs)


@mcp.tool(name="to_datetime")
def to_datetime(*args, **kwargs):
    """Convert argument to datetime."""
    return pandas.to_datetime(*args, **kwargs)


@mcp.tool(name="to_numeric")
def to_numeric(*args, **kwargs):
    """Convert argument to a numeric type."""
    return pandas.to_numeric(*args, **kwargs)


@mcp.tool(name="to_pickle")
def to_pickle(*args, **kwargs):
    """Pickle (serialize) object to file."""
    return pandas.to_pickle(*args, **kwargs)


@mcp.tool(name="to_timedelta")
def to_timedelta(*args, **kwargs):
    """Convert argument to timedelta."""
    return pandas.to_timedelta(*args, **kwargs)


@mcp.tool(name="unique")
def unique(*args, **kwargs):
    """Return unique values based on a hash table."""
    return pandas.unique(*args, **kwargs)


@mcp.tool(name="value_counts")
def value_counts(*args, **kwargs):
    """Compute a histogram of the counts of non-null values."""
    return pandas.value_counts(*args, **kwargs)


@mcp.tool(name="wide_to_long")
def wide_to_long(*args, **kwargs):
    """Unpivot a DataFrame from wide to long format."""
    return pandas.wide_to_long(*args, **kwargs)


@mcp.tool(name="construct_array_type")
def construct_array_type(*args, **kwargs):
    """Return the array type associated with this dtype."""
    return pandas.ArrowDtype.construct_array_type(*args, **kwargs)


@mcp.tool(name="construct_from_string")
def construct_from_string(*args, **kwargs):
    """Construct this type from a string."""
    return pandas.ArrowDtype.construct_from_string(*args, **kwargs)


@mcp.tool(name="construct_array_type")
def construct_array_type(*args, **kwargs):
    """Return the array type associated with this dtype."""
    return pandas.BooleanDtype.construct_array_type(*args, **kwargs)


@mcp.tool(name="add_categories")
def add_categories(*args, **kwargs):
    """Add new categories."""
    return pandas.Categorical.add_categories(*args, **kwargs)


@mcp.tool(name="argsort")
def argsort(*args, **kwargs):
    """Return the indices that would sort the Categorical."""
    return pandas.Categorical.argsort(*args, **kwargs)


@mcp.tool(name="as_ordered")
def as_ordered(*args, **kwargs):
    """Set the Categorical to be ordered."""
    return pandas.Categorical.as_ordered(*args, **kwargs)


@mcp.tool(name="as_unordered")
def as_unordered(*args, **kwargs):
    """Set the Categorical to be unordered."""
    return pandas.Categorical.as_unordered(*args, **kwargs)


@mcp.tool(name="astype")
def astype(*args, **kwargs):
    """Coerce this type to another dtype

Parameters
----------
dtype : numpy dtype or pandas type
copy : bool, default True
    By default, astype always returns a newly allocated object."""
    return pandas.Categorical.astype(*args, **kwargs)


@mcp.tool(name="check_for_ordered")
def check_for_ordered(*args, **kwargs):
    """assert that we are ordered."""
    return pandas.Categorical.check_for_ordered(*args, **kwargs)


@mcp.tool(name="describe")
def describe(*args, **kwargs):
    """Describes this Categorical

Returns
-------
description: `DataFrame`
    A dataframe with frequency and counts by category."""
    return pandas.Categorical.describe(*args, **kwargs)


@mcp.tool(name="equals")
def equals(*args, **kwargs):
    """Returns True if categorical arrays are equal."""
    return pandas.Categorical.equals(*args, **kwargs)


@mcp.tool(name="from_codes")
def from_codes(*args, **kwargs):
    """Make a Categorical type from codes and categories or dtype."""
    return pandas.Categorical.from_codes(*args, **kwargs)


@mcp.tool(name="isin")
def isin(*args, **kwargs):
    """Check whether `values` are contained in Categorical."""
    return pandas.Categorical.isin(*args, **kwargs)


@mcp.tool(name="isna")
def isna(*args, **kwargs):
    """Detect missing values

Missing values (-1 in."""
    return pandas.Categorical.isna(*args, **kwargs)


@mcp.tool(name="isna")
def isna(*args, **kwargs):
    """Detect missing values

Missing values (-1 in."""
    return pandas.Categorical.isna(*args, **kwargs)


@mcp.tool(name="map")
def map(*args, **kwargs):
    """Map categories using an input mapping or function."""
    return pandas.Categorical.map(*args, **kwargs)


@mcp.tool(name="max")
def max(*args, **kwargs):
    """The maximum value of the object."""
    return pandas.Categorical.max(*args, **kwargs)


@mcp.tool(name="memory_usage")
def memory_usage(*args, **kwargs):
    """Memory usage of my values

Parameters
----------
deep : bool
    Introspect the data deeply, interrogate
    `object` dtypes for system-level memory consumption

Returns
-------
bytes used

Notes
-----
Memory usage does not include memory consumed by elements that
are not components of the array if deep=False

See Also
--------
numpy."""
    return pandas.Categorical.memory_usage(*args, **kwargs)


@mcp.tool(name="min")
def min(*args, **kwargs):
    """The minimum value of the object."""
    return pandas.Categorical.min(*args, **kwargs)


@mcp.tool(name="notna")
def notna(*args, **kwargs):
    """Inverse of isna

Both missing values (-1 in."""
    return pandas.Categorical.notna(*args, **kwargs)


@mcp.tool(name="notna")
def notna(*args, **kwargs):
    """Inverse of isna

Both missing values (-1 in."""
    return pandas.Categorical.notna(*args, **kwargs)


@mcp.tool(name="remove_categories")
def remove_categories(*args, **kwargs):
    """Remove the specified categories."""
    return pandas.Categorical.remove_categories(*args, **kwargs)


@mcp.tool(name="remove_unused_categories")
def remove_unused_categories(*args, **kwargs):
    """Remove categories which are not used."""
    return pandas.Categorical.remove_unused_categories(*args, **kwargs)


@mcp.tool(name="rename_categories")
def rename_categories(*args, **kwargs):
    """Rename categories."""
    return pandas.Categorical.rename_categories(*args, **kwargs)


@mcp.tool(name="reorder_categories")
def reorder_categories(*args, **kwargs):
    """Reorder categories as specified in new_categories."""
    return pandas.Categorical.reorder_categories(*args, **kwargs)


@mcp.tool(name="set_categories")
def set_categories(*args, **kwargs):
    """Set the categories to the specified new categories."""
    return pandas.Categorical.set_categories(*args, **kwargs)


@mcp.tool(name="set_ordered")
def set_ordered(*args, **kwargs):
    """Set the ordered attribute to the boolean value."""
    return pandas.Categorical.set_ordered(*args, **kwargs)


@mcp.tool(name="sort_values")
def sort_values(*args, **kwargs):
    """Sort the Categorical by category value returning a new
Categorical by default."""
    return pandas.Categorical.sort_values(*args, **kwargs)


@mcp.tool(name="to_list")
def to_list(*args, **kwargs):
    """Alias for tolist."""
    return pandas.Categorical.to_list(*args, **kwargs)


@mcp.tool(name="unique")
def unique(*args, **kwargs):
    """Return the ``Categorical`` which ``categories`` and ``codes`` are
unique."""
    return pandas.Categorical.unique(*args, **kwargs)


@mcp.tool(name="value_counts")
def value_counts(*args, **kwargs):
    """Return a Series containing counts of each category."""
    return pandas.Categorical.value_counts(*args, **kwargs)


@mcp.tool(name="construct_array_type")
def construct_array_type(*args, **kwargs):
    """Return the array type associated with this dtype."""
    return pandas.CategoricalDtype.construct_array_type(*args, **kwargs)


@mcp.tool(name="construct_from_string")
def construct_from_string(*args, **kwargs):
    """Construct a CategoricalDtype from a string."""
    return pandas.CategoricalDtype.construct_from_string(*args, **kwargs)


@mcp.tool(name="update_dtype")
def update_dtype(*args, **kwargs):
    """Returns a CategoricalDtype with categories and ordered taken from dtype
if specified, otherwise falling back to self if unspecified

Parameters
----------
dtype : CategoricalDtype

Returns
-------
new_dtype : CategoricalDtype."""
    return pandas.CategoricalDtype.update_dtype(*args, **kwargs)


@mcp.tool(name="validate_categories")
def validate_categories(*args, **kwargs):
    """Validates that we have good categories

Parameters
----------
categories : array-like
fastpath : bool
    Whether to skip nan and uniqueness checks

Returns
-------
categories : Index."""
    return pandas.CategoricalDtype.validate_categories(*args, **kwargs)


@mcp.tool(name="validate_ordered")
def validate_ordered(*args, **kwargs):
    """Validates that we have a valid ordered parameter."""
    return pandas.CategoricalDtype.validate_ordered(*args, **kwargs)


@mcp.tool(name="equals")
def equals(*args, **kwargs):
    """Determine if two CategoricalIndex objects contain the same elements."""
    return pandas.CategoricalIndex.equals(*args, **kwargs)


@mcp.tool(name="map")
def map(*args, **kwargs):
    """Map values using input an input mapping or function."""
    return pandas.CategoricalIndex.map(*args, **kwargs)


@mcp.tool(name="reindex")
def reindex(*args, **kwargs):
    """Create index with target's values (move/add/delete values as necessary)

Returns
-------
new_index : pd."""
    return pandas.CategoricalIndex.reindex(*args, **kwargs)


@mcp.tool(name="add")
def add(*args, **kwargs):
    """Get Addition of dataframe and other, element-wise (binary operator `add`)."""
    return pandas.DataFrame.add(*args, **kwargs)


@mcp.tool(name="aggregate")
def aggregate(*args, **kwargs):
    """Aggregate using one or more operations over the specified axis."""
    return pandas.DataFrame.aggregate(*args, **kwargs)


@mcp.tool(name="aggregate")
def aggregate(*args, **kwargs):
    """Aggregate using one or more operations over the specified axis."""
    return pandas.DataFrame.aggregate(*args, **kwargs)


@mcp.tool(name="all")
def all(*args, **kwargs):
    """Return whether all elements are True, potentially over an axis."""
    return pandas.DataFrame.all(*args, **kwargs)


@mcp.tool(name="any")
def any(*args, **kwargs):
    """Return whether any element is True, potentially over an axis."""
    return pandas.DataFrame.any(*args, **kwargs)


@mcp.tool(name="apply")
def apply(*args, **kwargs):
    """Apply a function along an axis of the DataFrame."""
    return pandas.DataFrame.apply(*args, **kwargs)


@mcp.tool(name="applymap")
def applymap(*args, **kwargs):
    """Apply a function to a Dataframe elementwise."""
    return pandas.DataFrame.applymap(*args, **kwargs)


@mcp.tool(name="assign")
def assign(*args, **kwargs):
    """Assign new columns to a DataFrame."""
    return pandas.DataFrame.assign(*args, **kwargs)


@mcp.tool(name="combine")
def combine(*args, **kwargs):
    """Perform column-wise combine with another DataFrame."""
    return pandas.DataFrame.combine(*args, **kwargs)


@mcp.tool(name="combine_first")
def combine_first(*args, **kwargs):
    """Update null elements with value in the same location in `other`."""
    return pandas.DataFrame.combine_first(*args, **kwargs)


@mcp.tool(name="compare")
def compare(*args, **kwargs):
    """Compare to another DataFrame and show the differences."""
    return pandas.DataFrame.compare(*args, **kwargs)


@mcp.tool(name="corr")
def corr(*args, **kwargs):
    """Compute pairwise correlation of columns, excluding NA/null values."""
    return pandas.DataFrame.corr(*args, **kwargs)


@mcp.tool(name="corrwith")
def corrwith(*args, **kwargs):
    """Compute pairwise correlation."""
    return pandas.DataFrame.corrwith(*args, **kwargs)


@mcp.tool(name="count")
def count(*args, **kwargs):
    """Count non-NA cells for each column or row."""
    return pandas.DataFrame.count(*args, **kwargs)


@mcp.tool(name="cov")
def cov(*args, **kwargs):
    """Compute pairwise covariance of columns, excluding NA/null values."""
    return pandas.DataFrame.cov(*args, **kwargs)


@mcp.tool(name="cummax")
def cummax(*args, **kwargs):
    """Return cumulative maximum over a DataFrame or Series axis."""
    return pandas.DataFrame.cummax(*args, **kwargs)


@mcp.tool(name="cummin")
def cummin(*args, **kwargs):
    """Return cumulative minimum over a DataFrame or Series axis."""
    return pandas.DataFrame.cummin(*args, **kwargs)


@mcp.tool(name="cumprod")
def cumprod(*args, **kwargs):
    """Return cumulative product over a DataFrame or Series axis."""
    return pandas.DataFrame.cumprod(*args, **kwargs)


@mcp.tool(name="cumsum")
def cumsum(*args, **kwargs):
    """Return cumulative sum over a DataFrame or Series axis."""
    return pandas.DataFrame.cumsum(*args, **kwargs)


@mcp.tool(name="diff")
def diff(*args, **kwargs):
    """First discrete difference of element."""
    return pandas.DataFrame.diff(*args, **kwargs)


@mcp.tool(name="truediv")
def truediv(*args, **kwargs):
    """Get Floating division of dataframe and other, element-wise (binary operator `truediv`)."""
    return pandas.DataFrame.truediv(*args, **kwargs)


@mcp.tool(name="truediv")
def truediv(*args, **kwargs):
    """Get Floating division of dataframe and other, element-wise (binary operator `truediv`)."""
    return pandas.DataFrame.truediv(*args, **kwargs)


@mcp.tool(name="dot")
def dot(*args, **kwargs):
    """Compute the matrix multiplication between the DataFrame and other."""
    return pandas.DataFrame.dot(*args, **kwargs)


@mcp.tool(name="drop")
def drop(*args, **kwargs):
    """Drop specified labels from rows or columns."""
    return pandas.DataFrame.drop(*args, **kwargs)


@mcp.tool(name="drop_duplicates")
def drop_duplicates(*args, **kwargs):
    """Return DataFrame with duplicate rows removed."""
    return pandas.DataFrame.drop_duplicates(*args, **kwargs)


@mcp.tool(name="dropna")
def dropna(*args, **kwargs):
    """Remove missing values."""
    return pandas.DataFrame.dropna(*args, **kwargs)


@mcp.tool(name="duplicated")
def duplicated(*args, **kwargs):
    """Return boolean Series denoting duplicate rows."""
    return pandas.DataFrame.duplicated(*args, **kwargs)


@mcp.tool(name="eq")
def eq(*args, **kwargs):
    """Get Equal to of dataframe and other, element-wise (binary operator `eq`)."""
    return pandas.DataFrame.eq(*args, **kwargs)


@mcp.tool(name="eval")
def eval(*args, **kwargs):
    """Evaluate a string describing operations on DataFrame columns."""
    return pandas.DataFrame.eval(*args, **kwargs)


@mcp.tool(name="explode")
def explode(*args, **kwargs):
    """Transform each element of a list-like to a row, replicating index values."""
    return pandas.DataFrame.explode(*args, **kwargs)


@mcp.tool(name="floordiv")
def floordiv(*args, **kwargs):
    """Get Integer division of dataframe and other, element-wise (binary operator `floordiv`)."""
    return pandas.DataFrame.floordiv(*args, **kwargs)


@mcp.tool(name="from_dict")
def from_dict(*args, **kwargs):
    """Construct DataFrame from dict of array-like or dicts."""
    return pandas.DataFrame.from_dict(*args, **kwargs)


@mcp.tool(name="from_records")
def from_records(*args, **kwargs):
    """Convert structured or record ndarray to DataFrame."""
    return pandas.DataFrame.from_records(*args, **kwargs)


@mcp.tool(name="ge")
def ge(*args, **kwargs):
    """Get Greater than or equal to of dataframe and other, element-wise (binary operator `ge`)."""
    return pandas.DataFrame.ge(*args, **kwargs)


@mcp.tool(name="groupby")
def groupby(*args, **kwargs):
    """Group DataFrame using a mapper or by a Series of columns."""
    return pandas.DataFrame.groupby(*args, **kwargs)


@mcp.tool(name="gt")
def gt(*args, **kwargs):
    """Get Greater than of dataframe and other, element-wise (binary operator `gt`)."""
    return pandas.DataFrame.gt(*args, **kwargs)


@mcp.tool(name="idxmax")
def idxmax(*args, **kwargs):
    """Return index of first occurrence of maximum over requested axis."""
    return pandas.DataFrame.idxmax(*args, **kwargs)


@mcp.tool(name="idxmin")
def idxmin(*args, **kwargs):
    """Return index of first occurrence of minimum over requested axis."""
    return pandas.DataFrame.idxmin(*args, **kwargs)


@mcp.tool(name="info")
def info(*args, **kwargs):
    """Print a concise summary of a DataFrame."""
    return pandas.DataFrame.info(*args, **kwargs)


@mcp.tool(name="insert")
def insert(*args, **kwargs):
    """Insert column into DataFrame at specified location."""
    return pandas.DataFrame.insert(*args, **kwargs)


@mcp.tool(name="isetitem")
def isetitem(*args, **kwargs):
    """Set the given value in the column with position `loc`."""
    return pandas.DataFrame.isetitem(*args, **kwargs)


@mcp.tool(name="isin")
def isin(*args, **kwargs):
    """Whether each element in the DataFrame is contained in values."""
    return pandas.DataFrame.isin(*args, **kwargs)


@mcp.tool(name="isna")
def isna(*args, **kwargs):
    """Detect missing values."""
    return pandas.DataFrame.isna(*args, **kwargs)


@mcp.tool(name="isnull")
def isnull(*args, **kwargs):
    """DataFrame."""
    return pandas.DataFrame.isnull(*args, **kwargs)


@mcp.tool(name="items")
def items(*args, **kwargs):
    """Iterate over (column name, Series) pairs."""
    return pandas.DataFrame.items(*args, **kwargs)


@mcp.tool(name="iterrows")
def iterrows(*args, **kwargs):
    """Iterate over DataFrame rows as (index, Series) pairs."""
    return pandas.DataFrame.iterrows(*args, **kwargs)


@mcp.tool(name="itertuples")
def itertuples(*args, **kwargs):
    """Iterate over DataFrame rows as namedtuples."""
    return pandas.DataFrame.itertuples(*args, **kwargs)


@mcp.tool(name="join")
def join(*args, **kwargs):
    """Join columns of another DataFrame."""
    return pandas.DataFrame.join(*args, **kwargs)


@mcp.tool(name="kurt")
def kurt(*args, **kwargs):
    """Return unbiased kurtosis over requested axis."""
    return pandas.DataFrame.kurt(*args, **kwargs)


@mcp.tool(name="kurt")
def kurt(*args, **kwargs):
    """Return unbiased kurtosis over requested axis."""
    return pandas.DataFrame.kurt(*args, **kwargs)


@mcp.tool(name="le")
def le(*args, **kwargs):
    """Get Less than or equal to of dataframe and other, element-wise (binary operator `le`)."""
    return pandas.DataFrame.le(*args, **kwargs)


@mcp.tool(name="lt")
def lt(*args, **kwargs):
    """Get Less than of dataframe and other, element-wise (binary operator `lt`)."""
    return pandas.DataFrame.lt(*args, **kwargs)


@mcp.tool(name="map")
def map(*args, **kwargs):
    """Apply a function to a Dataframe elementwise."""
    return pandas.DataFrame.map(*args, **kwargs)


@mcp.tool(name="max")
def max(*args, **kwargs):
    """Return the maximum of the values over the requested axis."""
    return pandas.DataFrame.max(*args, **kwargs)


@mcp.tool(name="mean")
def mean(*args, **kwargs):
    """Return the mean of the values over the requested axis."""
    return pandas.DataFrame.mean(*args, **kwargs)


@mcp.tool(name="median")
def median(*args, **kwargs):
    """Return the median of the values over the requested axis."""
    return pandas.DataFrame.median(*args, **kwargs)


@mcp.tool(name="melt")
def melt(*args, **kwargs):
    """Unpivot a DataFrame from wide to long format, optionally leaving identifiers set."""
    return pandas.DataFrame.melt(*args, **kwargs)


@mcp.tool(name="memory_usage")
def memory_usage(*args, **kwargs):
    """Return the memory usage of each column in bytes."""
    return pandas.DataFrame.memory_usage(*args, **kwargs)


@mcp.tool(name="merge")
def merge(*args, **kwargs):
    """Merge DataFrame or named Series objects with a database-style join."""
    return pandas.DataFrame.merge(*args, **kwargs)


@mcp.tool(name="min")
def min(*args, **kwargs):
    """Return the minimum of the values over the requested axis."""
    return pandas.DataFrame.min(*args, **kwargs)


@mcp.tool(name="mod")
def mod(*args, **kwargs):
    """Get Modulo of dataframe and other, element-wise (binary operator `mod`)."""
    return pandas.DataFrame.mod(*args, **kwargs)


@mcp.tool(name="mode")
def mode(*args, **kwargs):
    """Get the mode(s) of each element along the selected axis."""
    return pandas.DataFrame.mode(*args, **kwargs)


@mcp.tool(name="mul")
def mul(*args, **kwargs):
    """Get Multiplication of dataframe and other, element-wise (binary operator `mul`)."""
    return pandas.DataFrame.mul(*args, **kwargs)


@mcp.tool(name="mul")
def mul(*args, **kwargs):
    """Get Multiplication of dataframe and other, element-wise (binary operator `mul`)."""
    return pandas.DataFrame.mul(*args, **kwargs)


@mcp.tool(name="ne")
def ne(*args, **kwargs):
    """Get Not equal to of dataframe and other, element-wise (binary operator `ne`)."""
    return pandas.DataFrame.ne(*args, **kwargs)


@mcp.tool(name="nlargest")
def nlargest(*args, **kwargs):
    """Return the first `n` rows ordered by `columns` in descending order."""
    return pandas.DataFrame.nlargest(*args, **kwargs)


@mcp.tool(name="notna")
def notna(*args, **kwargs):
    """Detect existing (non-missing) values."""
    return pandas.DataFrame.notna(*args, **kwargs)


@mcp.tool(name="notnull")
def notnull(*args, **kwargs):
    """DataFrame."""
    return pandas.DataFrame.notnull(*args, **kwargs)


@mcp.tool(name="nsmallest")
def nsmallest(*args, **kwargs):
    """Return the first `n` rows ordered by `columns` in ascending order."""
    return pandas.DataFrame.nsmallest(*args, **kwargs)


@mcp.tool(name="nunique")
def nunique(*args, **kwargs):
    """Count number of distinct elements in specified axis."""
    return pandas.DataFrame.nunique(*args, **kwargs)


@mcp.tool(name="pivot")
def pivot(*args, **kwargs):
    """Return reshaped DataFrame organized by given index / column values."""
    return pandas.DataFrame.pivot(*args, **kwargs)


@mcp.tool(name="pivot_table")
def pivot_table(*args, **kwargs):
    """Create a spreadsheet-style pivot table as a DataFrame."""
    return pandas.DataFrame.pivot_table(*args, **kwargs)


@mcp.tool(name="pop")
def pop(*args, **kwargs):
    """Return item and drop from frame."""
    return pandas.DataFrame.pop(*args, **kwargs)


@mcp.tool(name="pow")
def pow(*args, **kwargs):
    """Get Exponential power of dataframe and other, element-wise (binary operator `pow`)."""
    return pandas.DataFrame.pow(*args, **kwargs)


@mcp.tool(name="prod")
def prod(*args, **kwargs):
    """Return the product of the values over the requested axis."""
    return pandas.DataFrame.prod(*args, **kwargs)


@mcp.tool(name="prod")
def prod(*args, **kwargs):
    """Return the product of the values over the requested axis."""
    return pandas.DataFrame.prod(*args, **kwargs)


@mcp.tool(name="quantile")
def quantile(*args, **kwargs):
    """Return values at the given quantile over requested axis."""
    return pandas.DataFrame.quantile(*args, **kwargs)


@mcp.tool(name="query")
def query(*args, **kwargs):
    """Query the columns of a DataFrame with a boolean expression."""
    return pandas.DataFrame.query(*args, **kwargs)


@mcp.tool(name="radd")
def radd(*args, **kwargs):
    """Get Addition of dataframe and other, element-wise (binary operator `radd`)."""
    return pandas.DataFrame.radd(*args, **kwargs)


@mcp.tool(name="rtruediv")
def rtruediv(*args, **kwargs):
    """Get Floating division of dataframe and other, element-wise (binary operator `rtruediv`)."""
    return pandas.DataFrame.rtruediv(*args, **kwargs)


@mcp.tool(name="reindex")
def reindex(*args, **kwargs):
    """Conform DataFrame to new index with optional filling logic."""
    return pandas.DataFrame.reindex(*args, **kwargs)


@mcp.tool(name="rename")
def rename(*args, **kwargs):
    """Rename columns or index labels."""
    return pandas.DataFrame.rename(*args, **kwargs)


@mcp.tool(name="reorder_levels")
def reorder_levels(*args, **kwargs):
    """Rearrange index levels using input order."""
    return pandas.DataFrame.reorder_levels(*args, **kwargs)


@mcp.tool(name="reset_index")
def reset_index(*args, **kwargs):
    """Reset the index, or a level of it."""
    return pandas.DataFrame.reset_index(*args, **kwargs)


@mcp.tool(name="rfloordiv")
def rfloordiv(*args, **kwargs):
    """Get Integer division of dataframe and other, element-wise (binary operator `rfloordiv`)."""
    return pandas.DataFrame.rfloordiv(*args, **kwargs)


@mcp.tool(name="rmod")
def rmod(*args, **kwargs):
    """Get Modulo of dataframe and other, element-wise (binary operator `rmod`)."""
    return pandas.DataFrame.rmod(*args, **kwargs)


@mcp.tool(name="rmul")
def rmul(*args, **kwargs):
    """Get Multiplication of dataframe and other, element-wise (binary operator `rmul`)."""
    return pandas.DataFrame.rmul(*args, **kwargs)


@mcp.tool(name="round")
def round(*args, **kwargs):
    """Round a DataFrame to a variable number of decimal places."""
    return pandas.DataFrame.round(*args, **kwargs)


@mcp.tool(name="rpow")
def rpow(*args, **kwargs):
    """Get Exponential power of dataframe and other, element-wise (binary operator `rpow`)."""
    return pandas.DataFrame.rpow(*args, **kwargs)


@mcp.tool(name="rsub")
def rsub(*args, **kwargs):
    """Get Subtraction of dataframe and other, element-wise (binary operator `rsub`)."""
    return pandas.DataFrame.rsub(*args, **kwargs)


@mcp.tool(name="rtruediv")
def rtruediv(*args, **kwargs):
    """Get Floating division of dataframe and other, element-wise (binary operator `rtruediv`)."""
    return pandas.DataFrame.rtruediv(*args, **kwargs)


@mcp.tool(name="select_dtypes")
def select_dtypes(*args, **kwargs):
    """Return a subset of the DataFrame's columns based on the column dtypes."""
    return pandas.DataFrame.select_dtypes(*args, **kwargs)


@mcp.tool(name="sem")
def sem(*args, **kwargs):
    """Return unbiased standard error of the mean over requested axis."""
    return pandas.DataFrame.sem(*args, **kwargs)


@mcp.tool(name="set_axis")
def set_axis(*args, **kwargs):
    """Assign desired index to given axis."""
    return pandas.DataFrame.set_axis(*args, **kwargs)


@mcp.tool(name="set_index")
def set_index(*args, **kwargs):
    """Set the DataFrame index using existing columns."""
    return pandas.DataFrame.set_index(*args, **kwargs)


@mcp.tool(name="shift")
def shift(*args, **kwargs):
    """Shift index by desired number of periods with an optional time `freq`."""
    return pandas.DataFrame.shift(*args, **kwargs)


@mcp.tool(name="skew")
def skew(*args, **kwargs):
    """Return unbiased skew over requested axis."""
    return pandas.DataFrame.skew(*args, **kwargs)


@mcp.tool(name="sort_index")
def sort_index(*args, **kwargs):
    """Sort object by labels (along an axis)."""
    return pandas.DataFrame.sort_index(*args, **kwargs)


@mcp.tool(name="sort_values")
def sort_values(*args, **kwargs):
    """Sort by the values along either axis."""
    return pandas.DataFrame.sort_values(*args, **kwargs)


@mcp.tool(name="stack")
def stack(*args, **kwargs):
    """Stack the prescribed level(s) from columns to index."""
    return pandas.DataFrame.stack(*args, **kwargs)


@mcp.tool(name="std")
def std(*args, **kwargs):
    """Return sample standard deviation over requested axis."""
    return pandas.DataFrame.std(*args, **kwargs)


@mcp.tool(name="sub")
def sub(*args, **kwargs):
    """Get Subtraction of dataframe and other, element-wise (binary operator `sub`)."""
    return pandas.DataFrame.sub(*args, **kwargs)


@mcp.tool(name="sub")
def sub(*args, **kwargs):
    """Get Subtraction of dataframe and other, element-wise (binary operator `sub`)."""
    return pandas.DataFrame.sub(*args, **kwargs)


@mcp.tool(name="sum")
def sum(*args, **kwargs):
    """Return the sum of the values over the requested axis."""
    return pandas.DataFrame.sum(*args, **kwargs)


@mcp.tool(name="swaplevel")
def swaplevel(*args, **kwargs):
    """Swap levels i and j in a :class:`MultiIndex`."""
    return pandas.DataFrame.swaplevel(*args, **kwargs)


@mcp.tool(name="to_dict")
def to_dict(*args, **kwargs):
    """Convert the DataFrame to a dictionary."""
    return pandas.DataFrame.to_dict(*args, **kwargs)


@mcp.tool(name="to_feather")
def to_feather(*args, **kwargs):
    """Write a DataFrame to the binary Feather format."""
    return pandas.DataFrame.to_feather(*args, **kwargs)


@mcp.tool(name="to_gbq")
def to_gbq(*args, **kwargs):
    """Write a DataFrame to a Google BigQuery table."""
    return pandas.DataFrame.to_gbq(*args, **kwargs)


@mcp.tool(name="to_html")
def to_html(*args, **kwargs):
    """Render a DataFrame as an HTML table."""
    return pandas.DataFrame.to_html(*args, **kwargs)


@mcp.tool(name="to_markdown")
def to_markdown(*args, **kwargs):
    """Print DataFrame in Markdown-friendly format."""
    return pandas.DataFrame.to_markdown(*args, **kwargs)


@mcp.tool(name="to_numpy")
def to_numpy(*args, **kwargs):
    """Convert the DataFrame to a NumPy array."""
    return pandas.DataFrame.to_numpy(*args, **kwargs)


@mcp.tool(name="to_orc")
def to_orc(*args, **kwargs):
    """Write a DataFrame to the ORC format."""
    return pandas.DataFrame.to_orc(*args, **kwargs)


@mcp.tool(name="to_parquet")
def to_parquet(*args, **kwargs):
    """Write a DataFrame to the binary parquet format."""
    return pandas.DataFrame.to_parquet(*args, **kwargs)


@mcp.tool(name="to_period")
def to_period(*args, **kwargs):
    """Convert DataFrame from DatetimeIndex to PeriodIndex."""
    return pandas.DataFrame.to_period(*args, **kwargs)


@mcp.tool(name="to_records")
def to_records(*args, **kwargs):
    """Convert DataFrame to a NumPy record array."""
    return pandas.DataFrame.to_records(*args, **kwargs)


@mcp.tool(name="to_stata")
def to_stata(*args, **kwargs):
    """Export DataFrame object to Stata dta format."""
    return pandas.DataFrame.to_stata(*args, **kwargs)


@mcp.tool(name="to_string")
def to_string(*args, **kwargs):
    """Render a DataFrame to a console-friendly tabular output."""
    return pandas.DataFrame.to_string(*args, **kwargs)


@mcp.tool(name="to_timestamp")
def to_timestamp(*args, **kwargs):
    """Cast to DatetimeIndex of timestamps, at *beginning* of period."""
    return pandas.DataFrame.to_timestamp(*args, **kwargs)


@mcp.tool(name="to_xml")
def to_xml(*args, **kwargs):
    """Render a DataFrame to an XML document."""
    return pandas.DataFrame.to_xml(*args, **kwargs)


@mcp.tool(name="transform")
def transform(*args, **kwargs):
    """Call ``func`` on self producing a DataFrame with the same axis shape as self."""
    return pandas.DataFrame.transform(*args, **kwargs)


@mcp.tool(name="transpose")
def transpose(*args, **kwargs):
    """Transpose index and columns."""
    return pandas.DataFrame.transpose(*args, **kwargs)


@mcp.tool(name="truediv")
def truediv(*args, **kwargs):
    """Get Floating division of dataframe and other, element-wise (binary operator `truediv`)."""
    return pandas.DataFrame.truediv(*args, **kwargs)


@mcp.tool(name="unstack")
def unstack(*args, **kwargs):
    """Pivot a level of the (necessarily hierarchical) index labels."""
    return pandas.DataFrame.unstack(*args, **kwargs)


@mcp.tool(name="update")
def update(*args, **kwargs):
    """Modify in place using non-NA values from another DataFrame."""
    return pandas.DataFrame.update(*args, **kwargs)


@mcp.tool(name="value_counts")
def value_counts(*args, **kwargs):
    """Return a Series containing the frequency of each distinct row in the Dataframe."""
    return pandas.DataFrame.value_counts(*args, **kwargs)


@mcp.tool(name="var")
def var(*args, **kwargs):
    """Return unbiased variance over requested axis."""
    return pandas.DataFrame.var(*args, **kwargs)


@mcp.tool(name="get_loc")
def get_loc(*args, **kwargs):
    """Get integer location for requested label

Returns
-------
loc : int."""
    return pandas.DatetimeIndex.get_loc(*args, **kwargs)


@mcp.tool(name="indexer_at_time")
def indexer_at_time(*args, **kwargs):
    """Return index locations of values at particular time of day."""
    return pandas.DatetimeIndex.indexer_at_time(*args, **kwargs)


@mcp.tool(name="indexer_between_time")
def indexer_between_time(*args, **kwargs):
    """Return index locations of values between particular times of day."""
    return pandas.DatetimeIndex.indexer_between_time(*args, **kwargs)


@mcp.tool(name="isocalendar")
def isocalendar(*args, **kwargs):
    """Calculate year, week, and day according to the ISO 8601 standard."""
    return pandas.DatetimeIndex.isocalendar(*args, **kwargs)


@mcp.tool(name="slice_indexer")
def slice_indexer(*args, **kwargs):
    """Return indexer for specified label slice."""
    return pandas.DatetimeIndex.slice_indexer(*args, **kwargs)


@mcp.tool(name="snap")
def snap(*args, **kwargs):
    """Snap time stamps to nearest occurring frequency."""
    return pandas.DatetimeIndex.snap(*args, **kwargs)


@mcp.tool(name="strftime")
def strftime(*args, **kwargs):
    """Convert to Index using specified date_format."""
    return pandas.DatetimeIndex.strftime(*args, **kwargs)


@mcp.tool(name="to_julian_date")
def to_julian_date(*args, **kwargs):
    """Convert Datetime Array to float64 ndarray of Julian Dates."""
    return pandas.DatetimeIndex.to_julian_date(*args, **kwargs)


@mcp.tool(name="tz_convert")
def tz_convert(*args, **kwargs):
    """Convert tz-aware Datetime Array/Index from one time zone to another."""
    return pandas.DatetimeIndex.tz_convert(*args, **kwargs)


@mcp.tool(name="tz_localize")
def tz_localize(*args, **kwargs):
    """Localize tz-naive Datetime Array/Index to tz-aware Datetime Array/Index."""
    return pandas.DatetimeIndex.tz_localize(*args, **kwargs)


@mcp.tool(name="construct_array_type")
def construct_array_type(*args, **kwargs):
    """Return the array type associated with this dtype."""
    return pandas.DatetimeTZDtype.construct_array_type(*args, **kwargs)


@mcp.tool(name="construct_from_string")
def construct_from_string(*args, **kwargs):
    """Construct a DatetimeTZDtype from a string."""
    return pandas.DatetimeTZDtype.construct_from_string(*args, **kwargs)


@mcp.tool(name="close")
def close(*args, **kwargs):
    """close io if necessary."""
    return pandas.ExcelFile.close(*args, **kwargs)


@mcp.tool(name="parse")
def parse(*args, **kwargs):
    """Parse specified sheet(s) into a DataFrame."""
    return pandas.ExcelFile.parse(*args, **kwargs)


@mcp.tool(name="check_extension")
def check_extension(*args, **kwargs):
    """checks that path's extension against the Writer's supported
extensions."""
    return pandas.ExcelWriter.check_extension(*args, **kwargs)


@mcp.tool(name="close")
def close(*args, **kwargs):
    """synonym for save, to make it more file-like."""
    return pandas.ExcelWriter.close(*args, **kwargs)


@mcp.tool(name="append")
def append(*args, **kwargs):
    """Append to Table in file."""
    return pandas.HDFStore.append(*args, **kwargs)


@mcp.tool(name="append_to_multiple")
def append_to_multiple(*args, **kwargs):
    """Append to multiple tables

Parameters
----------
d : a dict of table_name to table_columns, None is acceptable as the
    values of one node (this will get all the remaining columns)
value : a pandas object
selector : a string that designates the indexable table; all of its
    columns will be designed as data_columns, unless data_columns is
    passed, in which case these are used
data_columns : list of columns to create as data columns, or True to
    use all columns
dropna : if evaluates to True, drop rows from all tables if any single
         row in each table has all NaN."""
    return pandas.HDFStore.append_to_multiple(*args, **kwargs)


@mcp.tool(name="close")
def close(*args, **kwargs):
    """Close the PyTables file handle."""
    return pandas.HDFStore.close(*args, **kwargs)


@mcp.tool(name="copy")
def copy(*args, **kwargs):
    """Copy the existing store to a new file, updating in place."""
    return pandas.HDFStore.copy(*args, **kwargs)


@mcp.tool(name="create_table_index")
def create_table_index(*args, **kwargs):
    """Create a pytables index on the table."""
    return pandas.HDFStore.create_table_index(*args, **kwargs)


@mcp.tool(name="flush")
def flush(*args, **kwargs):
    """Force all buffered modifications to be written to disk."""
    return pandas.HDFStore.flush(*args, **kwargs)


@mcp.tool(name="get")
def get(*args, **kwargs):
    """Retrieve pandas object stored in file."""
    return pandas.HDFStore.get(*args, **kwargs)


@mcp.tool(name="get_node")
def get_node(*args, **kwargs):
    """return the node with the key or None if it does not exist."""
    return pandas.HDFStore.get_node(*args, **kwargs)


@mcp.tool(name="get_storer")
def get_storer(*args, **kwargs):
    """return the storer object for a key, raise if not in the file."""
    return pandas.HDFStore.get_storer(*args, **kwargs)


@mcp.tool(name="groups")
def groups(*args, **kwargs):
    """Return a list of all the top-level nodes."""
    return pandas.HDFStore.groups(*args, **kwargs)


@mcp.tool(name="info")
def info(*args, **kwargs):
    """Print detailed information on the store."""
    return pandas.HDFStore.info(*args, **kwargs)


@mcp.tool(name="items")
def items(*args, **kwargs):
    """iterate on key->group."""
    return pandas.HDFStore.items(*args, **kwargs)


@mcp.tool(name="keys")
def keys(*args, **kwargs):
    """Return a list of keys corresponding to objects stored in HDFStore."""
    return pandas.HDFStore.keys(*args, **kwargs)


@mcp.tool(name="open")
def open(*args, **kwargs):
    """Open the file in the specified mode

Parameters
----------
mode : {'a', 'w', 'r', 'r+'}, default 'a'
    See HDFStore docstring or tables."""
    return pandas.HDFStore.open(*args, **kwargs)


@mcp.tool(name="put")
def put(*args, **kwargs):
    """Store object in HDFStore."""
    return pandas.HDFStore.put(*args, **kwargs)


@mcp.tool(name="remove")
def remove(*args, **kwargs):
    """Remove pandas object partially by specifying the where condition

Parameters
----------
key : str
    Node to remove or delete rows from
where : list of Term (or convertible) objects, optional
start : integer (defaults to None), row number to start selection
stop  : integer (defaults to None), row number to stop selection

Returns
-------
number of rows removed (or None if not a Table)

Raises
------
raises KeyError if key is not a valid store."""
    return pandas.HDFStore.remove(*args, **kwargs)


@mcp.tool(name="select")
def select(*args, **kwargs):
    """Retrieve pandas object stored in file, optionally based on where criteria."""
    return pandas.HDFStore.select(*args, **kwargs)


@mcp.tool(name="select_as_coordinates")
def select_as_coordinates(*args, **kwargs):
    """return the selection as an Index."""
    return pandas.HDFStore.select_as_coordinates(*args, **kwargs)


@mcp.tool(name="select_as_multiple")
def select_as_multiple(*args, **kwargs):
    """Retrieve pandas objects from multiple tables."""
    return pandas.HDFStore.select_as_multiple(*args, **kwargs)


@mcp.tool(name="select_column")
def select_column(*args, **kwargs):
    """return a single column from the table."""
    return pandas.HDFStore.select_column(*args, **kwargs)


@mcp.tool(name="walk")
def walk(*args, **kwargs):
    """Walk the pytables group hierarchy for pandas objects."""
    return pandas.HDFStore.walk(*args, **kwargs)


@mcp.tool(name="all")
def all(*args, **kwargs):
    """Return whether all elements are Truthy."""
    return pandas.Index.all(*args, **kwargs)


@mcp.tool(name="any")
def any(*args, **kwargs):
    """Return whether any element is Truthy."""
    return pandas.Index.any(*args, **kwargs)


@mcp.tool(name="append")
def append(*args, **kwargs):
    """Append a collection of Index options together."""
    return pandas.Index.append(*args, **kwargs)


@mcp.tool(name="argmax")
def argmax(*args, **kwargs):
    """Return int position of the largest value in the Series."""
    return pandas.Index.argmax(*args, **kwargs)


@mcp.tool(name="argmin")
def argmin(*args, **kwargs):
    """Return int position of the smallest value in the Series."""
    return pandas.Index.argmin(*args, **kwargs)


@mcp.tool(name="argsort")
def argsort(*args, **kwargs):
    """Return the integer indices that would sort the index."""
    return pandas.Index.argsort(*args, **kwargs)


@mcp.tool(name="asof")
def asof(*args, **kwargs):
    """Return the label from the index, or, if not present, the previous one."""
    return pandas.Index.asof(*args, **kwargs)


@mcp.tool(name="asof_locs")
def asof_locs(*args, **kwargs):
    """Return the locations (indices) of labels in the index."""
    return pandas.Index.asof_locs(*args, **kwargs)


@mcp.tool(name="astype")
def astype(*args, **kwargs):
    """Create an Index with values cast to dtypes."""
    return pandas.Index.astype(*args, **kwargs)


@mcp.tool(name="copy")
def copy(*args, **kwargs):
    """Make a copy of this object."""
    return pandas.Index.copy(*args, **kwargs)


@mcp.tool(name="delete")
def delete(*args, **kwargs):
    """Make new Index with passed location(-s) deleted."""
    return pandas.Index.delete(*args, **kwargs)


@mcp.tool(name="diff")
def diff(*args, **kwargs):
    """Computes the difference between consecutive values in the Index object."""
    return pandas.Index.diff(*args, **kwargs)


@mcp.tool(name="difference")
def difference(*args, **kwargs):
    """Return a new Index with elements of index not in `other`."""
    return pandas.Index.difference(*args, **kwargs)


@mcp.tool(name="drop")
def drop(*args, **kwargs):
    """Make new Index with passed list of labels deleted."""
    return pandas.Index.drop(*args, **kwargs)


@mcp.tool(name="drop_duplicates")
def drop_duplicates(*args, **kwargs):
    """Return Index with duplicate values removed."""
    return pandas.Index.drop_duplicates(*args, **kwargs)


@mcp.tool(name="droplevel")
def droplevel(*args, **kwargs):
    """Return index with requested level(s) removed."""
    return pandas.Index.droplevel(*args, **kwargs)


@mcp.tool(name="dropna")
def dropna(*args, **kwargs):
    """Return Index without NA/NaN values."""
    return pandas.Index.dropna(*args, **kwargs)


@mcp.tool(name="duplicated")
def duplicated(*args, **kwargs):
    """Indicate duplicate index values."""
    return pandas.Index.duplicated(*args, **kwargs)


@mcp.tool(name="equals")
def equals(*args, **kwargs):
    """Determine if two Index object are equal."""
    return pandas.Index.equals(*args, **kwargs)


@mcp.tool(name="fillna")
def fillna(*args, **kwargs):
    """Fill NA/NaN values with the specified value."""
    return pandas.Index.fillna(*args, **kwargs)


@mcp.tool(name="format")
def format(*args, **kwargs):
    """Render a string representation of the Index."""
    return pandas.Index.format(*args, **kwargs)


@mcp.tool(name="get_indexer")
def get_indexer(*args, **kwargs):
    """Compute indexer and mask for new index given the current index."""
    return pandas.Index.get_indexer(*args, **kwargs)


@mcp.tool(name="get_indexer_for")
def get_indexer_for(*args, **kwargs):
    """Guaranteed return of an indexer even when non-unique."""
    return pandas.Index.get_indexer_for(*args, **kwargs)


@mcp.tool(name="get_indexer_non_unique")
def get_indexer_non_unique(*args, **kwargs):
    """Compute indexer and mask for new index given the current index."""
    return pandas.Index.get_indexer_non_unique(*args, **kwargs)


@mcp.tool(name="get_loc")
def get_loc(*args, **kwargs):
    """Get integer location, slice or boolean mask for requested label."""
    return pandas.Index.get_loc(*args, **kwargs)


@mcp.tool(name="get_slice_bound")
def get_slice_bound(*args, **kwargs):
    """Calculate slice bound that corresponds to given label."""
    return pandas.Index.get_slice_bound(*args, **kwargs)


@mcp.tool(name="groupby")
def groupby(*args, **kwargs):
    """Group the index labels by a given array of values."""
    return pandas.Index.groupby(*args, **kwargs)


@mcp.tool(name="holds_integer")
def holds_integer(*args, **kwargs):
    """Whether the type is an integer type."""
    return pandas.Index.holds_integer(*args, **kwargs)


@mcp.tool(name="identical")
def identical(*args, **kwargs):
    """Similar to equals, but checks that object attributes and types are also equal."""
    return pandas.Index.identical(*args, **kwargs)


@mcp.tool(name="infer_objects")
def infer_objects(*args, **kwargs):
    """If we have an object dtype, try to infer a non-object dtype."""
    return pandas.Index.infer_objects(*args, **kwargs)


@mcp.tool(name="insert")
def insert(*args, **kwargs):
    """Make new Index inserting new item at location."""
    return pandas.Index.insert(*args, **kwargs)


@mcp.tool(name="intersection")
def intersection(*args, **kwargs):
    """Form the intersection of two Index objects."""
    return pandas.Index.intersection(*args, **kwargs)


@mcp.tool(name="is_")
def is_(*args, **kwargs):
    """More flexible, faster check like ``is`` but that works through views."""
    return pandas.Index.is_(*args, **kwargs)


@mcp.tool(name="is_boolean")
def is_boolean(*args, **kwargs):
    """Check if the Index only consists of booleans."""
    return pandas.Index.is_boolean(*args, **kwargs)


@mcp.tool(name="is_categorical")
def is_categorical(*args, **kwargs):
    """Check if the Index holds categorical data."""
    return pandas.Index.is_categorical(*args, **kwargs)


@mcp.tool(name="is_floating")
def is_floating(*args, **kwargs):
    """Check if the Index is a floating type."""
    return pandas.Index.is_floating(*args, **kwargs)


@mcp.tool(name="is_integer")
def is_integer(*args, **kwargs):
    """Check if the Index only consists of integers."""
    return pandas.Index.is_integer(*args, **kwargs)


@mcp.tool(name="is_interval")
def is_interval(*args, **kwargs):
    """Check if the Index holds Interval objects."""
    return pandas.Index.is_interval(*args, **kwargs)


@mcp.tool(name="is_numeric")
def is_numeric(*args, **kwargs):
    """Check if the Index only consists of numeric data."""
    return pandas.Index.is_numeric(*args, **kwargs)


@mcp.tool(name="is_object")
def is_object(*args, **kwargs):
    """Check if the Index is of the object dtype."""
    return pandas.Index.is_object(*args, **kwargs)


@mcp.tool(name="isin")
def isin(*args, **kwargs):
    """Return a boolean array where the index values are in `values`."""
    return pandas.Index.isin(*args, **kwargs)


@mcp.tool(name="isna")
def isna(*args, **kwargs):
    """Detect missing values."""
    return pandas.Index.isna(*args, **kwargs)


@mcp.tool(name="isna")
def isna(*args, **kwargs):
    """Detect missing values."""
    return pandas.Index.isna(*args, **kwargs)


@mcp.tool(name="join")
def join(*args, **kwargs):
    """Compute join_index and indexers to conform data structures to the new index."""
    return pandas.Index.join(*args, **kwargs)


@mcp.tool(name="map")
def map(*args, **kwargs):
    """Map values using an input mapping or function."""
    return pandas.Index.map(*args, **kwargs)


@mcp.tool(name="max")
def max(*args, **kwargs):
    """Return the maximum value of the Index."""
    return pandas.Index.max(*args, **kwargs)


@mcp.tool(name="memory_usage")
def memory_usage(*args, **kwargs):
    """Memory usage of the values."""
    return pandas.Index.memory_usage(*args, **kwargs)


@mcp.tool(name="min")
def min(*args, **kwargs):
    """Return the minimum value of the Index."""
    return pandas.Index.min(*args, **kwargs)


@mcp.tool(name="notna")
def notna(*args, **kwargs):
    """Detect existing (non-missing) values."""
    return pandas.Index.notna(*args, **kwargs)


@mcp.tool(name="notna")
def notna(*args, **kwargs):
    """Detect existing (non-missing) values."""
    return pandas.Index.notna(*args, **kwargs)


@mcp.tool(name="putmask")
def putmask(*args, **kwargs):
    """Return a new Index of the values set with the mask."""
    return pandas.Index.putmask(*args, **kwargs)


@mcp.tool(name="ravel")
def ravel(*args, **kwargs):
    """Return a view on self."""
    return pandas.Index.ravel(*args, **kwargs)


@mcp.tool(name="reindex")
def reindex(*args, **kwargs):
    """Create index with target's values."""
    return pandas.Index.reindex(*args, **kwargs)


@mcp.tool(name="rename")
def rename(*args, **kwargs):
    """Alter Index or MultiIndex name."""
    return pandas.Index.rename(*args, **kwargs)


@mcp.tool(name="repeat")
def repeat(*args, **kwargs):
    """Repeat elements of a Index."""
    return pandas.Index.repeat(*args, **kwargs)


@mcp.tool(name="round")
def round(*args, **kwargs):
    """Round each value in the Index to the given number of decimals."""
    return pandas.Index.round(*args, **kwargs)


@mcp.tool(name="set_names")
def set_names(*args, **kwargs):
    """Set Index or MultiIndex name."""
    return pandas.Index.set_names(*args, **kwargs)


@mcp.tool(name="shift")
def shift(*args, **kwargs):
    """Shift index by desired number of time frequency increments."""
    return pandas.Index.shift(*args, **kwargs)


@mcp.tool(name="slice_indexer")
def slice_indexer(*args, **kwargs):
    """Compute the slice indexer for input labels and step."""
    return pandas.Index.slice_indexer(*args, **kwargs)


@mcp.tool(name="slice_locs")
def slice_locs(*args, **kwargs):
    """Compute slice locations for input labels."""
    return pandas.Index.slice_locs(*args, **kwargs)


@mcp.tool(name="sort")
def sort(*args, **kwargs):
    """Use sort_values instead."""
    return pandas.Index.sort(*args, **kwargs)


@mcp.tool(name="sort_values")
def sort_values(*args, **kwargs):
    """Return a sorted copy of the index."""
    return pandas.Index.sort_values(*args, **kwargs)


@mcp.tool(name="sortlevel")
def sortlevel(*args, **kwargs):
    """For internal compatibility with the Index API."""
    return pandas.Index.sortlevel(*args, **kwargs)


@mcp.tool(name="symmetric_difference")
def symmetric_difference(*args, **kwargs):
    """Compute the symmetric difference of two Index objects."""
    return pandas.Index.symmetric_difference(*args, **kwargs)


@mcp.tool(name="take")
def take(*args, **kwargs):
    """Return a new Index of the values selected by the indices."""
    return pandas.Index.take(*args, **kwargs)


@mcp.tool(name="to_flat_index")
def to_flat_index(*args, **kwargs):
    """Identity method."""
    return pandas.Index.to_flat_index(*args, **kwargs)


@mcp.tool(name="to_frame")
def to_frame(*args, **kwargs):
    """Create a DataFrame with a column containing the Index."""
    return pandas.Index.to_frame(*args, **kwargs)


@mcp.tool(name="to_series")
def to_series(*args, **kwargs):
    """Create a Series with both index and values equal to the index keys."""
    return pandas.Index.to_series(*args, **kwargs)


@mcp.tool(name="union")
def union(*args, **kwargs):
    """Form the union of two Index objects."""
    return pandas.Index.union(*args, **kwargs)


@mcp.tool(name="unique")
def unique(*args, **kwargs):
    """Return unique values in the index."""
    return pandas.Index.unique(*args, **kwargs)


@mcp.tool(name="view")
def view(*args, **kwargs):
    """Executes the view operation."""
    return pandas.Index.view(*args, **kwargs)


@mcp.tool(name="where")
def where(*args, **kwargs):
    """Replace values where the condition is False."""
    return pandas.Index.where(*args, **kwargs)


@mcp.tool(name="construct_array_type")
def construct_array_type(*args, **kwargs):
    """Return the array type associated with this dtype."""
    return pandas.IntervalDtype.construct_array_type(*args, **kwargs)


@mcp.tool(name="construct_from_string")
def construct_from_string(*args, **kwargs):
    """attempt to construct this type from a string, raise a TypeError
if its not possible."""
    return pandas.IntervalDtype.construct_from_string(*args, **kwargs)


@mcp.tool(name="is_dtype")
def is_dtype(*args, **kwargs):
    """Return a boolean if we if the passed type is an actual dtype that we
can match (via string or type)."""
    return pandas.IntervalDtype.is_dtype(*args, **kwargs)


@mcp.tool(name="from_arrays")
def from_arrays(*args, **kwargs):
    """Construct from two arrays defining the left and right bounds."""
    return pandas.IntervalIndex.from_arrays(*args, **kwargs)


@mcp.tool(name="from_breaks")
def from_breaks(*args, **kwargs):
    """Construct an IntervalIndex from an array of splits."""
    return pandas.IntervalIndex.from_breaks(*args, **kwargs)


@mcp.tool(name="from_tuples")
def from_tuples(*args, **kwargs):
    """Construct an IntervalIndex from an array-like of tuples."""
    return pandas.IntervalIndex.from_tuples(*args, **kwargs)


@mcp.tool(name="get_indexer_non_unique")
def get_indexer_non_unique(*args, **kwargs):
    """Compute indexer and mask for new index given the current index."""
    return pandas.IntervalIndex.get_indexer_non_unique(*args, **kwargs)


@mcp.tool(name="get_loc")
def get_loc(*args, **kwargs):
    """Get integer location, slice or boolean mask for requested label."""
    return pandas.IntervalIndex.get_loc(*args, **kwargs)


@mcp.tool(name="memory_usage")
def memory_usage(*args, **kwargs):
    """Memory usage of the values."""
    return pandas.IntervalIndex.memory_usage(*args, **kwargs)


@mcp.tool(name="duplicated")
def duplicated(*args, **kwargs):
    """Indicate duplicate index values."""
    return pandas.MultiIndex.duplicated(*args, **kwargs)


@mcp.tool(name="append")
def append(*args, **kwargs):
    """Append a collection of Index options together."""
    return pandas.MultiIndex.append(*args, **kwargs)


@mcp.tool(name="argsort")
def argsort(*args, **kwargs):
    """Return the integer indices that would sort the index."""
    return pandas.MultiIndex.argsort(*args, **kwargs)


@mcp.tool(name="astype")
def astype(*args, **kwargs):
    """Create an Index with values cast to dtypes."""
    return pandas.MultiIndex.astype(*args, **kwargs)


@mcp.tool(name="copy")
def copy(*args, **kwargs):
    """Make a copy of this object."""
    return pandas.MultiIndex.copy(*args, **kwargs)


@mcp.tool(name="delete")
def delete(*args, **kwargs):
    """Make new index with passed location deleted

Returns
-------
new_index : MultiIndex."""
    return pandas.MultiIndex.delete(*args, **kwargs)


@mcp.tool(name="drop")
def drop(*args, **kwargs):
    """Make a new :class:`pandas."""
    return pandas.MultiIndex.drop(*args, **kwargs)


@mcp.tool(name="dropna")
def dropna(*args, **kwargs):
    """Return Index without NA/NaN values."""
    return pandas.MultiIndex.dropna(*args, **kwargs)


@mcp.tool(name="duplicated")
def duplicated(*args, **kwargs):
    """Indicate duplicate index values."""
    return pandas.MultiIndex.duplicated(*args, **kwargs)


@mcp.tool(name="equal_levels")
def equal_levels(*args, **kwargs):
    """Return True if the levels of both MultiIndex objects are the same."""
    return pandas.MultiIndex.equal_levels(*args, **kwargs)


@mcp.tool(name="equals")
def equals(*args, **kwargs):
    """Determines if two MultiIndex objects have the same labeling information
(the levels themselves do not necessarily have to be the same)

See Also
--------
equal_levels."""
    return pandas.MultiIndex.equals(*args, **kwargs)


@mcp.tool(name="fillna")
def fillna(*args, **kwargs):
    """fillna is not implemented for MultiIndex."""
    return pandas.MultiIndex.fillna(*args, **kwargs)


@mcp.tool(name="format")
def format(*args, **kwargs):
    """Render a string representation of the Index."""
    return pandas.MultiIndex.format(*args, **kwargs)


@mcp.tool(name="from_arrays")
def from_arrays(*args, **kwargs):
    """Convert arrays to MultiIndex."""
    return pandas.MultiIndex.from_arrays(*args, **kwargs)


@mcp.tool(name="from_frame")
def from_frame(*args, **kwargs):
    """Make a MultiIndex from a DataFrame."""
    return pandas.MultiIndex.from_frame(*args, **kwargs)


@mcp.tool(name="from_product")
def from_product(*args, **kwargs):
    """Make a MultiIndex from the cartesian product of multiple iterables."""
    return pandas.MultiIndex.from_product(*args, **kwargs)


@mcp.tool(name="from_tuples")
def from_tuples(*args, **kwargs):
    """Convert list of tuples to MultiIndex."""
    return pandas.MultiIndex.from_tuples(*args, **kwargs)


@mcp.tool(name="get_level_values")
def get_level_values(*args, **kwargs):
    """Return vector of label values for requested level."""
    return pandas.MultiIndex.get_level_values(*args, **kwargs)


@mcp.tool(name="get_loc")
def get_loc(*args, **kwargs):
    """Get location for a label or a tuple of labels."""
    return pandas.MultiIndex.get_loc(*args, **kwargs)


@mcp.tool(name="get_loc_level")
def get_loc_level(*args, **kwargs):
    """Get location and sliced index for requested label(s)/level(s)."""
    return pandas.MultiIndex.get_loc_level(*args, **kwargs)


@mcp.tool(name="get_locs")
def get_locs(*args, **kwargs):
    """Get location for a sequence of labels."""
    return pandas.MultiIndex.get_locs(*args, **kwargs)


@mcp.tool(name="get_slice_bound")
def get_slice_bound(*args, **kwargs):
    """For an ordered MultiIndex, compute slice bound
that corresponds to given label."""
    return pandas.MultiIndex.get_slice_bound(*args, **kwargs)


@mcp.tool(name="insert")
def insert(*args, **kwargs):
    """Make new MultiIndex inserting new item at location

Parameters
----------
loc : int
item : tuple
    Must be same length as number of levels in the MultiIndex

Returns
-------
new_index : Index."""
    return pandas.MultiIndex.insert(*args, **kwargs)


@mcp.tool(name="isin")
def isin(*args, **kwargs):
    """Return a boolean array where the index values are in `values`."""
    return pandas.MultiIndex.isin(*args, **kwargs)


@mcp.tool(name="memory_usage")
def memory_usage(*args, **kwargs):
    """Memory usage of the values."""
    return pandas.MultiIndex.memory_usage(*args, **kwargs)


@mcp.tool(name="putmask")
def putmask(*args, **kwargs):
    """Return a new MultiIndex of the values set with the mask."""
    return pandas.MultiIndex.putmask(*args, **kwargs)


@mcp.tool(name="remove_unused_levels")
def remove_unused_levels(*args, **kwargs):
    """Create new MultiIndex from current that removes unused levels."""
    return pandas.MultiIndex.remove_unused_levels(*args, **kwargs)


@mcp.tool(name="reorder_levels")
def reorder_levels(*args, **kwargs):
    """Rearrange levels using input order."""
    return pandas.MultiIndex.reorder_levels(*args, **kwargs)


@mcp.tool(name="repeat")
def repeat(*args, **kwargs):
    """Repeat elements of a MultiIndex."""
    return pandas.MultiIndex.repeat(*args, **kwargs)


@mcp.tool(name="set_codes")
def set_codes(*args, **kwargs):
    """Set new codes on MultiIndex."""
    return pandas.MultiIndex.set_codes(*args, **kwargs)


@mcp.tool(name="set_levels")
def set_levels(*args, **kwargs):
    """Set new levels on MultiIndex."""
    return pandas.MultiIndex.set_levels(*args, **kwargs)


@mcp.tool(name="slice_locs")
def slice_locs(*args, **kwargs):
    """For an ordered MultiIndex, compute the slice locations for input
labels."""
    return pandas.MultiIndex.slice_locs(*args, **kwargs)


@mcp.tool(name="sortlevel")
def sortlevel(*args, **kwargs):
    """Sort MultiIndex at the requested level."""
    return pandas.MultiIndex.sortlevel(*args, **kwargs)


@mcp.tool(name="swaplevel")
def swaplevel(*args, **kwargs):
    """Swap level i with level j."""
    return pandas.MultiIndex.swaplevel(*args, **kwargs)


@mcp.tool(name="take")
def take(*args, **kwargs):
    """Return a new MultiIndex of the values selected by the indices."""
    return pandas.MultiIndex.take(*args, **kwargs)


@mcp.tool(name="to_flat_index")
def to_flat_index(*args, **kwargs):
    """Convert a MultiIndex to an Index of Tuples containing the level values."""
    return pandas.MultiIndex.to_flat_index(*args, **kwargs)


@mcp.tool(name="to_frame")
def to_frame(*args, **kwargs):
    """Create a DataFrame with the levels of the MultiIndex as columns."""
    return pandas.MultiIndex.to_frame(*args, **kwargs)


@mcp.tool(name="truncate")
def truncate(*args, **kwargs):
    """Slice index between two labels / tuples, return new MultiIndex."""
    return pandas.MultiIndex.truncate(*args, **kwargs)


@mcp.tool(name="unique")
def unique(*args, **kwargs):
    """Return unique values in the index."""
    return pandas.MultiIndex.unique(*args, **kwargs)


@mcp.tool(name="view")
def view(*args, **kwargs):
    """this is defined as a copy with the same identity."""
    return pandas.MultiIndex.view(*args, **kwargs)


@mcp.tool(name="construct_array_type")
def construct_array_type(*args, **kwargs):
    """Return the array type associated with this dtype."""
    return pandas.PeriodDtype.construct_array_type(*args, **kwargs)


@mcp.tool(name="construct_from_string")
def construct_from_string(*args, **kwargs):
    """Strict construction from a string, raise a TypeError if not
possible."""
    return pandas.PeriodDtype.construct_from_string(*args, **kwargs)


@mcp.tool(name="is_dtype")
def is_dtype(*args, **kwargs):
    """Return a boolean if we if the passed type is an actual dtype that we
can match (via string or type)."""
    return pandas.PeriodDtype.is_dtype(*args, **kwargs)


@mcp.tool(name="asfreq")
def asfreq(*args, **kwargs):
    """Convert the PeriodArray to the specified frequency `freq`."""
    return pandas.PeriodIndex.asfreq(*args, **kwargs)


@mcp.tool(name="asof_locs")
def asof_locs(*args, **kwargs):
    """where : array of timestamps
mask : np."""
    return pandas.PeriodIndex.asof_locs(*args, **kwargs)


@mcp.tool(name="from_fields")
def from_fields(*args, **kwargs):
    """Executes the from_fields operation."""
    return pandas.PeriodIndex.from_fields(*args, **kwargs)


@mcp.tool(name="from_ordinals")
def from_ordinals(*args, **kwargs):
    """Executes the from_ordinals operation."""
    return pandas.PeriodIndex.from_ordinals(*args, **kwargs)


@mcp.tool(name="get_loc")
def get_loc(*args, **kwargs):
    """Get integer location for requested label."""
    return pandas.PeriodIndex.get_loc(*args, **kwargs)


@mcp.tool(name="shift")
def shift(*args, **kwargs):
    """Shift index by desired number of time frequency increments."""
    return pandas.PeriodIndex.shift(*args, **kwargs)


@mcp.tool(name="to_timestamp")
def to_timestamp(*args, **kwargs):
    """Cast to DatetimeArray/Index."""
    return pandas.PeriodIndex.to_timestamp(*args, **kwargs)


@mcp.tool(name="all")
def all(*args, **kwargs):
    """Return whether all elements are Truthy."""
    return pandas.RangeIndex.all(*args, **kwargs)


@mcp.tool(name="any")
def any(*args, **kwargs):
    """Return whether any element is Truthy."""
    return pandas.RangeIndex.any(*args, **kwargs)


@mcp.tool(name="argsort")
def argsort(*args, **kwargs):
    """Returns the indices that would sort the index and its
underlying data."""
    return pandas.RangeIndex.argsort(*args, **kwargs)


@mcp.tool(name="copy")
def copy(*args, **kwargs):
    """Make a copy of this object."""
    return pandas.RangeIndex.copy(*args, **kwargs)


@mcp.tool(name="delete")
def delete(*args, **kwargs):
    """Make new Index with passed location(-s) deleted."""
    return pandas.RangeIndex.delete(*args, **kwargs)


@mcp.tool(name="equals")
def equals(*args, **kwargs):
    """Determines if two Index objects contain the same elements."""
    return pandas.RangeIndex.equals(*args, **kwargs)


@mcp.tool(name="factorize")
def factorize(*args, **kwargs):
    """Encode the object as an enumerated type or categorical variable."""
    return pandas.RangeIndex.factorize(*args, **kwargs)


@mcp.tool(name="from_range")
def from_range(*args, **kwargs):
    """Create :class:`pandas."""
    return pandas.RangeIndex.from_range(*args, **kwargs)


@mcp.tool(name="get_loc")
def get_loc(*args, **kwargs):
    """Get integer location, slice or boolean mask for requested label."""
    return pandas.RangeIndex.get_loc(*args, **kwargs)


@mcp.tool(name="insert")
def insert(*args, **kwargs):
    """Make new Index inserting new item at location."""
    return pandas.RangeIndex.insert(*args, **kwargs)


@mcp.tool(name="max")
def max(*args, **kwargs):
    """The maximum value of the RangeIndex."""
    return pandas.RangeIndex.max(*args, **kwargs)


@mcp.tool(name="memory_usage")
def memory_usage(*args, **kwargs):
    """Memory usage of my values

Parameters
----------
deep : bool
    Introspect the data deeply, interrogate
    `object` dtypes for system-level memory consumption

Returns
-------
bytes used

Notes
-----
Memory usage does not include memory consumed by elements that
are not components of the array if deep=False

See Also
--------
numpy."""
    return pandas.RangeIndex.memory_usage(*args, **kwargs)


@mcp.tool(name="min")
def min(*args, **kwargs):
    """The minimum value of the RangeIndex."""
    return pandas.RangeIndex.min(*args, **kwargs)


@mcp.tool(name="sort_values")
def sort_values(*args, **kwargs):
    """Return a sorted copy of the index."""
    return pandas.RangeIndex.sort_values(*args, **kwargs)


@mcp.tool(name="symmetric_difference")
def symmetric_difference(*args, **kwargs):
    """Compute the symmetric difference of two Index objects."""
    return pandas.RangeIndex.symmetric_difference(*args, **kwargs)


@mcp.tool(name="take")
def take(*args, **kwargs):
    """Return a new Index of the values selected by the indices."""
    return pandas.RangeIndex.take(*args, **kwargs)


@mcp.tool(name="tolist")
def tolist(*args, **kwargs):
    """Return a list of the values."""
    return pandas.RangeIndex.tolist(*args, **kwargs)


@mcp.tool(name="add")
def add(*args, **kwargs):
    """Return Addition of series and other, element-wise (binary operator `add`)."""
    return pandas.Series.add(*args, **kwargs)


@mcp.tool(name="aggregate")
def aggregate(*args, **kwargs):
    """Aggregate using one or more operations over the specified axis."""
    return pandas.Series.aggregate(*args, **kwargs)


@mcp.tool(name="aggregate")
def aggregate(*args, **kwargs):
    """Aggregate using one or more operations over the specified axis."""
    return pandas.Series.aggregate(*args, **kwargs)


@mcp.tool(name="all")
def all(*args, **kwargs):
    """Return whether all elements are True, potentially over an axis."""
    return pandas.Series.all(*args, **kwargs)


@mcp.tool(name="any")
def any(*args, **kwargs):
    """Return whether any element is True, potentially over an axis."""
    return pandas.Series.any(*args, **kwargs)


@mcp.tool(name="apply")
def apply(*args, **kwargs):
    """Invoke function on values of Series."""
    return pandas.Series.apply(*args, **kwargs)


@mcp.tool(name="argsort")
def argsort(*args, **kwargs):
    """Return the integer indices that would sort the Series values."""
    return pandas.Series.argsort(*args, **kwargs)


@mcp.tool(name="autocorr")
def autocorr(*args, **kwargs):
    """Compute the lag-N autocorrelation."""
    return pandas.Series.autocorr(*args, **kwargs)


@mcp.tool(name="between")
def between(*args, **kwargs):
    """Return boolean Series equivalent to left <= series <= right."""
    return pandas.Series.between(*args, **kwargs)


@mcp.tool(name="case_when")
def case_when(*args, **kwargs):
    """Replace values where the conditions are True."""
    return pandas.Series.case_when(*args, **kwargs)


@mcp.tool(name="combine")
def combine(*args, **kwargs):
    """Combine the Series with a Series or scalar according to `func`."""
    return pandas.Series.combine(*args, **kwargs)


@mcp.tool(name="combine_first")
def combine_first(*args, **kwargs):
    """Update null elements with value in the same location in 'other'."""
    return pandas.Series.combine_first(*args, **kwargs)


@mcp.tool(name="compare")
def compare(*args, **kwargs):
    """Compare to another Series and show the differences."""
    return pandas.Series.compare(*args, **kwargs)


@mcp.tool(name="corr")
def corr(*args, **kwargs):
    """Compute correlation with `other` Series, excluding missing values."""
    return pandas.Series.corr(*args, **kwargs)


@mcp.tool(name="count")
def count(*args, **kwargs):
    """Return number of non-NA/null observations in the Series."""
    return pandas.Series.count(*args, **kwargs)


@mcp.tool(name="cov")
def cov(*args, **kwargs):
    """Compute covariance with Series, excluding missing values."""
    return pandas.Series.cov(*args, **kwargs)


@mcp.tool(name="cummax")
def cummax(*args, **kwargs):
    """Return cumulative maximum over a DataFrame or Series axis."""
    return pandas.Series.cummax(*args, **kwargs)


@mcp.tool(name="cummin")
def cummin(*args, **kwargs):
    """Return cumulative minimum over a DataFrame or Series axis."""
    return pandas.Series.cummin(*args, **kwargs)


@mcp.tool(name="cumprod")
def cumprod(*args, **kwargs):
    """Return cumulative product over a DataFrame or Series axis."""
    return pandas.Series.cumprod(*args, **kwargs)


@mcp.tool(name="cumsum")
def cumsum(*args, **kwargs):
    """Return cumulative sum over a DataFrame or Series axis."""
    return pandas.Series.cumsum(*args, **kwargs)


@mcp.tool(name="diff")
def diff(*args, **kwargs):
    """First discrete difference of element."""
    return pandas.Series.diff(*args, **kwargs)


@mcp.tool(name="truediv")
def truediv(*args, **kwargs):
    """Return Floating division of series and other, element-wise (binary operator `truediv`)."""
    return pandas.Series.truediv(*args, **kwargs)


@mcp.tool(name="truediv")
def truediv(*args, **kwargs):
    """Return Floating division of series and other, element-wise (binary operator `truediv`)."""
    return pandas.Series.truediv(*args, **kwargs)


@mcp.tool(name="divmod")
def divmod(*args, **kwargs):
    """Return Integer division and modulo of series and other, element-wise (binary operator `divmod`)."""
    return pandas.Series.divmod(*args, **kwargs)


@mcp.tool(name="dot")
def dot(*args, **kwargs):
    """Compute the dot product between the Series and the columns of other."""
    return pandas.Series.dot(*args, **kwargs)


@mcp.tool(name="drop")
def drop(*args, **kwargs):
    """Return Series with specified index labels removed."""
    return pandas.Series.drop(*args, **kwargs)


@mcp.tool(name="drop_duplicates")
def drop_duplicates(*args, **kwargs):
    """Return Series with duplicate values removed."""
    return pandas.Series.drop_duplicates(*args, **kwargs)


@mcp.tool(name="dropna")
def dropna(*args, **kwargs):
    """Return a new Series with missing values removed."""
    return pandas.Series.dropna(*args, **kwargs)


@mcp.tool(name="duplicated")
def duplicated(*args, **kwargs):
    """Indicate duplicate Series values."""
    return pandas.Series.duplicated(*args, **kwargs)


@mcp.tool(name="eq")
def eq(*args, **kwargs):
    """Return Equal to of series and other, element-wise (binary operator `eq`)."""
    return pandas.Series.eq(*args, **kwargs)


@mcp.tool(name="explode")
def explode(*args, **kwargs):
    """Transform each element of a list-like to a row."""
    return pandas.Series.explode(*args, **kwargs)


@mcp.tool(name="floordiv")
def floordiv(*args, **kwargs):
    """Return Integer division of series and other, element-wise (binary operator `floordiv`)."""
    return pandas.Series.floordiv(*args, **kwargs)


@mcp.tool(name="ge")
def ge(*args, **kwargs):
    """Return Greater than or equal to of series and other, element-wise (binary operator `ge`)."""
    return pandas.Series.ge(*args, **kwargs)


@mcp.tool(name="groupby")
def groupby(*args, **kwargs):
    """Group Series using a mapper or by a Series of columns."""
    return pandas.Series.groupby(*args, **kwargs)


@mcp.tool(name="gt")
def gt(*args, **kwargs):
    """Return Greater than of series and other, element-wise (binary operator `gt`)."""
    return pandas.Series.gt(*args, **kwargs)


@mcp.tool(name="idxmax")
def idxmax(*args, **kwargs):
    """Return the row label of the maximum value."""
    return pandas.Series.idxmax(*args, **kwargs)


@mcp.tool(name="idxmin")
def idxmin(*args, **kwargs):
    """Return the row label of the minimum value."""
    return pandas.Series.idxmin(*args, **kwargs)


@mcp.tool(name="info")
def info(*args, **kwargs):
    """Print a concise summary of a Series."""
    return pandas.Series.info(*args, **kwargs)


@mcp.tool(name="isin")
def isin(*args, **kwargs):
    """Whether elements in Series are contained in `values`."""
    return pandas.Series.isin(*args, **kwargs)


@mcp.tool(name="isna")
def isna(*args, **kwargs):
    """Detect missing values."""
    return pandas.Series.isna(*args, **kwargs)


@mcp.tool(name="isnull")
def isnull(*args, **kwargs):
    """Series."""
    return pandas.Series.isnull(*args, **kwargs)


@mcp.tool(name="items")
def items(*args, **kwargs):
    """Lazily iterate over (index, value) tuples."""
    return pandas.Series.items(*args, **kwargs)


@mcp.tool(name="keys")
def keys(*args, **kwargs):
    """Return alias for index."""
    return pandas.Series.keys(*args, **kwargs)


@mcp.tool(name="kurt")
def kurt(*args, **kwargs):
    """Return unbiased kurtosis over requested axis."""
    return pandas.Series.kurt(*args, **kwargs)


@mcp.tool(name="kurt")
def kurt(*args, **kwargs):
    """Return unbiased kurtosis over requested axis."""
    return pandas.Series.kurt(*args, **kwargs)


@mcp.tool(name="le")
def le(*args, **kwargs):
    """Return Less than or equal to of series and other, element-wise (binary operator `le`)."""
    return pandas.Series.le(*args, **kwargs)


@mcp.tool(name="lt")
def lt(*args, **kwargs):
    """Return Less than of series and other, element-wise (binary operator `lt`)."""
    return pandas.Series.lt(*args, **kwargs)


@mcp.tool(name="map")
def map(*args, **kwargs):
    """Map values of Series according to an input mapping or function."""
    return pandas.Series.map(*args, **kwargs)


@mcp.tool(name="max")
def max(*args, **kwargs):
    """Return the maximum of the values over the requested axis."""
    return pandas.Series.max(*args, **kwargs)


@mcp.tool(name="mean")
def mean(*args, **kwargs):
    """Return the mean of the values over the requested axis."""
    return pandas.Series.mean(*args, **kwargs)


@mcp.tool(name="median")
def median(*args, **kwargs):
    """Return the median of the values over the requested axis."""
    return pandas.Series.median(*args, **kwargs)


@mcp.tool(name="memory_usage")
def memory_usage(*args, **kwargs):
    """Return the memory usage of the Series."""
    return pandas.Series.memory_usage(*args, **kwargs)


@mcp.tool(name="min")
def min(*args, **kwargs):
    """Return the minimum of the values over the requested axis."""
    return pandas.Series.min(*args, **kwargs)


@mcp.tool(name="mod")
def mod(*args, **kwargs):
    """Return Modulo of series and other, element-wise (binary operator `mod`)."""
    return pandas.Series.mod(*args, **kwargs)


@mcp.tool(name="mode")
def mode(*args, **kwargs):
    """Return the mode(s) of the Series."""
    return pandas.Series.mode(*args, **kwargs)


@mcp.tool(name="mul")
def mul(*args, **kwargs):
    """Return Multiplication of series and other, element-wise (binary operator `mul`)."""
    return pandas.Series.mul(*args, **kwargs)


@mcp.tool(name="mul")
def mul(*args, **kwargs):
    """Return Multiplication of series and other, element-wise (binary operator `mul`)."""
    return pandas.Series.mul(*args, **kwargs)


@mcp.tool(name="ne")
def ne(*args, **kwargs):
    """Return Not equal to of series and other, element-wise (binary operator `ne`)."""
    return pandas.Series.ne(*args, **kwargs)


@mcp.tool(name="nlargest")
def nlargest(*args, **kwargs):
    """Return the largest `n` elements."""
    return pandas.Series.nlargest(*args, **kwargs)


@mcp.tool(name="notna")
def notna(*args, **kwargs):
    """Detect existing (non-missing) values."""
    return pandas.Series.notna(*args, **kwargs)


@mcp.tool(name="notnull")
def notnull(*args, **kwargs):
    """Series."""
    return pandas.Series.notnull(*args, **kwargs)


@mcp.tool(name="nsmallest")
def nsmallest(*args, **kwargs):
    """Return the smallest `n` elements."""
    return pandas.Series.nsmallest(*args, **kwargs)


@mcp.tool(name="pop")
def pop(*args, **kwargs):
    """Return item and drops from series."""
    return pandas.Series.pop(*args, **kwargs)


@mcp.tool(name="pow")
def pow(*args, **kwargs):
    """Return Exponential power of series and other, element-wise (binary operator `pow`)."""
    return pandas.Series.pow(*args, **kwargs)


@mcp.tool(name="prod")
def prod(*args, **kwargs):
    """Return the product of the values over the requested axis."""
    return pandas.Series.prod(*args, **kwargs)


@mcp.tool(name="prod")
def prod(*args, **kwargs):
    """Return the product of the values over the requested axis."""
    return pandas.Series.prod(*args, **kwargs)


@mcp.tool(name="quantile")
def quantile(*args, **kwargs):
    """Return value at the given quantile."""
    return pandas.Series.quantile(*args, **kwargs)


@mcp.tool(name="radd")
def radd(*args, **kwargs):
    """Return Addition of series and other, element-wise (binary operator `radd`)."""
    return pandas.Series.radd(*args, **kwargs)


@mcp.tool(name="ravel")
def ravel(*args, **kwargs):
    """Return the flattened underlying data as an ndarray or ExtensionArray."""
    return pandas.Series.ravel(*args, **kwargs)


@mcp.tool(name="rtruediv")
def rtruediv(*args, **kwargs):
    """Return Floating division of series and other, element-wise (binary operator `rtruediv`)."""
    return pandas.Series.rtruediv(*args, **kwargs)


@mcp.tool(name="rdivmod")
def rdivmod(*args, **kwargs):
    """Return Integer division and modulo of series and other, element-wise (binary operator `rdivmod`)."""
    return pandas.Series.rdivmod(*args, **kwargs)


@mcp.tool(name="reindex")
def reindex(*args, **kwargs):
    """Conform Series to new index with optional filling logic."""
    return pandas.Series.reindex(*args, **kwargs)


@mcp.tool(name="rename")
def rename(*args, **kwargs):
    """Alter Series index labels or name."""
    return pandas.Series.rename(*args, **kwargs)


@mcp.tool(name="rename_axis")
def rename_axis(*args, **kwargs):
    """Set the name of the axis for the index or columns."""
    return pandas.Series.rename_axis(*args, **kwargs)


@mcp.tool(name="reorder_levels")
def reorder_levels(*args, **kwargs):
    """Rearrange index levels using input order."""
    return pandas.Series.reorder_levels(*args, **kwargs)


@mcp.tool(name="repeat")
def repeat(*args, **kwargs):
    """Repeat elements of a Series."""
    return pandas.Series.repeat(*args, **kwargs)


@mcp.tool(name="reset_index")
def reset_index(*args, **kwargs):
    """Generate a new DataFrame or Series with the index reset."""
    return pandas.Series.reset_index(*args, **kwargs)


@mcp.tool(name="rfloordiv")
def rfloordiv(*args, **kwargs):
    """Return Integer division of series and other, element-wise (binary operator `rfloordiv`)."""
    return pandas.Series.rfloordiv(*args, **kwargs)


@mcp.tool(name="rmod")
def rmod(*args, **kwargs):
    """Return Modulo of series and other, element-wise (binary operator `rmod`)."""
    return pandas.Series.rmod(*args, **kwargs)


@mcp.tool(name="rmul")
def rmul(*args, **kwargs):
    """Return Multiplication of series and other, element-wise (binary operator `rmul`)."""
    return pandas.Series.rmul(*args, **kwargs)


@mcp.tool(name="round")
def round(*args, **kwargs):
    """Round each value in a Series to the given number of decimals."""
    return pandas.Series.round(*args, **kwargs)


@mcp.tool(name="rpow")
def rpow(*args, **kwargs):
    """Return Exponential power of series and other, element-wise (binary operator `rpow`)."""
    return pandas.Series.rpow(*args, **kwargs)


@mcp.tool(name="rsub")
def rsub(*args, **kwargs):
    """Return Subtraction of series and other, element-wise (binary operator `rsub`)."""
    return pandas.Series.rsub(*args, **kwargs)


@mcp.tool(name="rtruediv")
def rtruediv(*args, **kwargs):
    """Return Floating division of series and other, element-wise (binary operator `rtruediv`)."""
    return pandas.Series.rtruediv(*args, **kwargs)


@mcp.tool(name="searchsorted")
def searchsorted(*args, **kwargs):
    """Find indices where elements should be inserted to maintain order."""
    return pandas.Series.searchsorted(*args, **kwargs)


@mcp.tool(name="sem")
def sem(*args, **kwargs):
    """Return unbiased standard error of the mean over requested axis."""
    return pandas.Series.sem(*args, **kwargs)


@mcp.tool(name="set_axis")
def set_axis(*args, **kwargs):
    """Assign desired index to given axis."""
    return pandas.Series.set_axis(*args, **kwargs)


@mcp.tool(name="skew")
def skew(*args, **kwargs):
    """Return unbiased skew over requested axis."""
    return pandas.Series.skew(*args, **kwargs)


@mcp.tool(name="sort_index")
def sort_index(*args, **kwargs):
    """Sort Series by index labels."""
    return pandas.Series.sort_index(*args, **kwargs)


@mcp.tool(name="sort_values")
def sort_values(*args, **kwargs):
    """Sort by the values."""
    return pandas.Series.sort_values(*args, **kwargs)


@mcp.tool(name="std")
def std(*args, **kwargs):
    """Return sample standard deviation over requested axis."""
    return pandas.Series.std(*args, **kwargs)


@mcp.tool(name="sub")
def sub(*args, **kwargs):
    """Return Subtraction of series and other, element-wise (binary operator `sub`)."""
    return pandas.Series.sub(*args, **kwargs)


@mcp.tool(name="sub")
def sub(*args, **kwargs):
    """Return Subtraction of series and other, element-wise (binary operator `sub`)."""
    return pandas.Series.sub(*args, **kwargs)


@mcp.tool(name="sum")
def sum(*args, **kwargs):
    """Return the sum of the values over the requested axis."""
    return pandas.Series.sum(*args, **kwargs)


@mcp.tool(name="swaplevel")
def swaplevel(*args, **kwargs):
    """Swap levels i and j in a :class:`MultiIndex`."""
    return pandas.Series.swaplevel(*args, **kwargs)


@mcp.tool(name="to_dict")
def to_dict(*args, **kwargs):
    """Convert Series to {label -> value} dict or dict-like object."""
    return pandas.Series.to_dict(*args, **kwargs)


@mcp.tool(name="to_frame")
def to_frame(*args, **kwargs):
    """Convert Series to DataFrame."""
    return pandas.Series.to_frame(*args, **kwargs)


@mcp.tool(name="to_markdown")
def to_markdown(*args, **kwargs):
    """Print Series in Markdown-friendly format."""
    return pandas.Series.to_markdown(*args, **kwargs)


@mcp.tool(name="to_period")
def to_period(*args, **kwargs):
    """Convert Series from DatetimeIndex to PeriodIndex."""
    return pandas.Series.to_period(*args, **kwargs)


@mcp.tool(name="to_string")
def to_string(*args, **kwargs):
    """Render a string representation of the Series."""
    return pandas.Series.to_string(*args, **kwargs)


@mcp.tool(name="to_timestamp")
def to_timestamp(*args, **kwargs):
    """Cast to DatetimeIndex of Timestamps, at *beginning* of period."""
    return pandas.Series.to_timestamp(*args, **kwargs)


@mcp.tool(name="transform")
def transform(*args, **kwargs):
    """Call ``func`` on self producing a Series with the same axis shape as self."""
    return pandas.Series.transform(*args, **kwargs)


@mcp.tool(name="truediv")
def truediv(*args, **kwargs):
    """Return Floating division of series and other, element-wise (binary operator `truediv`)."""
    return pandas.Series.truediv(*args, **kwargs)


@mcp.tool(name="unique")
def unique(*args, **kwargs):
    """Return unique values of Series object."""
    return pandas.Series.unique(*args, **kwargs)


@mcp.tool(name="unstack")
def unstack(*args, **kwargs):
    """Unstack, also known as pivot, Series with MultiIndex to produce DataFrame."""
    return pandas.Series.unstack(*args, **kwargs)


@mcp.tool(name="update")
def update(*args, **kwargs):
    """Modify Series in place using values from passed Series."""
    return pandas.Series.update(*args, **kwargs)


@mcp.tool(name="var")
def var(*args, **kwargs):
    """Return unbiased variance over requested axis."""
    return pandas.Series.var(*args, **kwargs)


@mcp.tool(name="view")
def view(*args, **kwargs):
    """Create a new view of the Series."""
    return pandas.Series.view(*args, **kwargs)


@mcp.tool(name="construct_array_type")
def construct_array_type(*args, **kwargs):
    """Return the array type associated with this dtype."""
    return pandas.SparseDtype.construct_array_type(*args, **kwargs)


@mcp.tool(name="construct_from_string")
def construct_from_string(*args, **kwargs):
    """Construct a SparseDtype from a string form."""
    return pandas.SparseDtype.construct_from_string(*args, **kwargs)


@mcp.tool(name="is_dtype")
def is_dtype(*args, **kwargs):
    """Executes the is_dtype operation."""
    return pandas.SparseDtype.is_dtype(*args, **kwargs)


@mcp.tool(name="update_dtype")
def update_dtype(*args, **kwargs):
    """Convert the SparseDtype to a new dtype."""
    return pandas.SparseDtype.update_dtype(*args, **kwargs)


@mcp.tool(name="construct_array_type")
def construct_array_type(*args, **kwargs):
    """Return the array type associated with this dtype."""
    return pandas.StringDtype.construct_array_type(*args, **kwargs)


@mcp.tool(name="construct_from_string")
def construct_from_string(*args, **kwargs):
    """Construct a StringDtype from a string."""
    return pandas.StringDtype.construct_from_string(*args, **kwargs)


@mcp.tool(name="get_loc")
def get_loc(*args, **kwargs):
    """Get integer location for requested label

Returns
-------
loc : int, slice, or ndarray[int]."""
    return pandas.TimedeltaIndex.get_loc(*args, **kwargs)


@mcp.tool(name="combine")
def combine(*args, **kwargs):
    """Timestamp."""
    return pandas.Timestamp.combine(*args, **kwargs)


@mcp.tool(name="fromordinal")
def fromordinal(*args, **kwargs):
    """Construct a timestamp from a a proleptic Gregorian ordinal."""
    return pandas.Timestamp.fromordinal(*args, **kwargs)


@mcp.tool(name="fromtimestamp")
def fromtimestamp(*args, **kwargs):
    """Timestamp."""
    return pandas.Timestamp.fromtimestamp(*args, **kwargs)


@mcp.tool(name="now")
def now(*args, **kwargs):
    """Return new Timestamp object representing current time local to tz."""
    return pandas.Timestamp.now(*args, **kwargs)


@mcp.tool(name="strptime")
def strptime(*args, **kwargs):
    """Timestamp."""
    return pandas.Timestamp.strptime(*args, **kwargs)


@mcp.tool(name="today")
def today(*args, **kwargs):
    """Return the current time in the local timezone."""
    return pandas.Timestamp.today(*args, **kwargs)


@mcp.tool(name="utcfromtimestamp")
def utcfromtimestamp(*args, **kwargs):
    """Timestamp."""
    return pandas.Timestamp.utcfromtimestamp(*args, **kwargs)


@mcp.tool(name="utcnow")
def utcnow(*args, **kwargs):
    """Timestamp."""
    return pandas.Timestamp.utcnow(*args, **kwargs)




if __name__ == "__main__":
    mcp.run()
