"""Auto-generated MCP server for SQLite database operations.

Generated by auto-mcp.
Provides 18 tools for database management, CRUD operations, and queries.
"""

import sys
from pathlib import Path

# Add the module directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))

from mcp.server.fastmcp import FastMCP

import sqlite_tools

# Create MCP server
mcp = FastMCP(name="sqlite-tools")

# Tools

@mcp.tool(name="aggregate_query")
def aggregate_query(*args, **kwargs):
    """Run an aggregate query on a table."""
    return sqlite_tools.aggregate_query(*args, **kwargs)


@mcp.tool(name="connect_database")
def connect_database(*args, **kwargs):
    """Connect to a SQLite database."""
    return sqlite_tools.connect_database(*args, **kwargs)


@mcp.tool(name="count_rows")
def count_rows(*args, **kwargs):
    """Count rows in a table."""
    return sqlite_tools.count_rows(*args, **kwargs)


@mcp.tool(name="create_sample_data")
def create_sample_data(*args, **kwargs):
    """Create sample tables with test data."""
    return sqlite_tools.create_sample_data(*args, **kwargs)


@mcp.tool(name="create_table")
def create_table(*args, **kwargs):
    """Create a new table."""
    return sqlite_tools.create_table(*args, **kwargs)


@mcp.tool(name="delete_rows")
def delete_rows(*args, **kwargs):
    """Delete rows matching conditions."""
    return sqlite_tools.delete_rows(*args, **kwargs)


@mcp.tool(name="describe_table")
def describe_table(*args, **kwargs):
    """Get the schema of a table."""
    return sqlite_tools.describe_table(*args, **kwargs)


@mcp.tool(name="disconnect_database")
def disconnect_database(*args, **kwargs):
    """Close a database connection."""
    return sqlite_tools.disconnect_database(*args, **kwargs)


@mcp.tool(name="drop_table")
def drop_table(*args, **kwargs):
    """Drop a table."""
    return sqlite_tools.drop_table(*args, **kwargs)


@mcp.tool(name="execute_query")
def execute_query(*args, **kwargs):
    """Execute a SQL query and return results."""
    return sqlite_tools.execute_query(*args, **kwargs)


@mcp.tool(name="execute_script")
def execute_script(*args, **kwargs):
    """Execute a SQL script with multiple statements."""
    return sqlite_tools.execute_script(*args, **kwargs)


@mcp.tool(name="get_database_info")
def get_database_info(*args, **kwargs):
    """Get information about the database."""
    return sqlite_tools.get_database_info(*args, **kwargs)


@mcp.tool(name="insert_many")
def insert_many(*args, **kwargs):
    """Insert multiple rows into a table."""
    return sqlite_tools.insert_many(*args, **kwargs)


@mcp.tool(name="insert_row")
def insert_row(*args, **kwargs):
    """Insert a row into a table."""
    return sqlite_tools.insert_row(*args, **kwargs)


@mcp.tool(name="join_query")
def join_query(*args, **kwargs):
    """Execute a JOIN query between two tables."""
    return sqlite_tools.join_query(*args, **kwargs)


@mcp.tool(name="list_tables")
def list_tables(*args, **kwargs):
    """List all tables in the database."""
    return sqlite_tools.list_tables(*args, **kwargs)


@mcp.tool(name="select_all")
def select_all(*args, **kwargs):
    """Select all rows from a table."""
    return sqlite_tools.select_all(*args, **kwargs)


@mcp.tool(name="select_where")
def select_where(*args, **kwargs):
    """Select rows matching conditions."""
    return sqlite_tools.select_where(*args, **kwargs)


@mcp.tool(name="update_rows")
def update_rows(*args, **kwargs):
    """Update rows matching conditions."""
    return sqlite_tools.update_rows(*args, **kwargs)




if __name__ == "__main__":
    mcp.run()
